### ISSUE TITLE
数据库mysql中search_result中repo字段错误

### ISSUE THREAD

**Issue by xj90512** [madneal/gshark#102]
hello，
想问下，在扫描结果落到mysql后，去search_result表格里面查看到的repo信息是有问题的，
但从repo表里面去看，发现path以及project_id是所需要的数据信息，所以在search_result的截取信息里面是不是写错了
这两个表没办法去做数据关联，这部分有什么办法解决吗？

**Comment by madneal** [comment]
search_result 表格的 repo 当初应该没做好 gitlab 的兼容
