### ISSUE TITLE
配置好监控邮箱，但是显示发送失败

### ISSUE THREAD

**Issue by mrwpro** [madneal/gshark#115]
大佬好，请教一下，我是在虚拟机部署的gshark，然后在我配置好邮件设置后，测试发送显示发送失败，这个和我的网络环境有关吗？
![image](https://user-images.githubusercontent.com/90690030/172760950-3a996b9d-e98b-40ff-8cf8-ba8bc1e1759f.png)

**Comment by mrwpro** [comment]
虚拟机是可以通外网的

**Comment by madneal** [comment]
你可以看一下后台命令行打印的错误

**Comment by madneal** [comment]
secret 记得打码

**Comment by mrwpro** [comment]
打印错误为：535 Login Fail. Please enter your authorization code to login.，我百度了说是邮箱授权码的问题，但事实上我用的就是授权码，并且已经开启了邮件pop/smtp服务。

**Comment by madneal** [comment]
那这个应该是你邮箱配置的问题了，我自己使用的是QQ邮箱

**Comment by mrwpro** [comment]
大佬好，解决了，因为我是直接在网页上配置的邮箱，但是测试发送时候gshark是要去读config文件的，写进去web但是没写进去config，就会出现失败。以后会出一个批量添加规则的吗，我一条一条写很久

**Comment by madneal** [comment]
你可以直接通过数据库的形式加
