### ISSUE TITLE
对获取的数据进行第二次筛选过滤

### ISSUE THREAD

**Issue by mrwpro** [madneal/gshark#118]
大佬好，可不可以在现有的一层keywords基础上再加一层keywords两者是与的关系，比如我搜了几个域名类型的项目，然后再根据一些关键词（比如：password，root之类的）做一个碰撞监测，虽然web页面可以自行搜索，但是数据量非常大，经过两层碰撞监测的话，数据会很精准

**Comment by madneal** [comment]
已经添加这个功能
https://github.com/madneal/gshark/releases/tag/v1.1.0
