### ISSUE TITLE
状态开关提示权限不足

### ISSUE THREAD

**Issue by Nan3r** [madneal/gshark#126]
1.超管权限，在已经有的规则下，修改状态开关提示权限不足
2.修改规则不起作用

**Comment by madneal** [comment]
需要给 api 添加权限，可能是因为历史部署权限没有加进去

**Comment by madneal** [comment]
https://github.com/madneal/gshark/blob/master/sql.md#v098

**Comment by huangzexinmingyqf** [comment]
同样的问题，这个添加权限的命令，该在哪个文件下添加
全局搜索没找到sql.md (′゜ω。‵)
![image](https://user-images.githubusercontent.com/81756571/217160486-541995dc-cbc7-49e7-aad6-8698f5f749d5.png)

**Comment by madneal** [comment]
@huangzexinmingyqf  是哪一个 api 路由，你加进去就好了
