### ISSUE TITLE
自动创建数据库失败

### ISSUE THREAD

**Issue by Toy-godlike** [madneal/gshark#129]
error	自动创建数据库失败	{"err": "Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'JSON,PRIMARY KEY (`id`),INDEX idx_search_result_deleted_at (`deleted_at`))' at line 1"}

**Comment by madneal** [comment]
mysql 版本是不是过低

**Comment by Tender-Liu** [comment]
mysql 版本9.0

**Comment by Tender-Liu** [comment]
mysql  Ver 8.0.31 数据库的版本

**Comment by yggo** [comment]
`v1.0.2`版本gshark，`5.7.26`版本MySQL，按照`readme`安装后数据库里没有初始数据，搜索issue后插入了两个系统账户，登录时提示`/menu/getMenu`接口没有权限，`casbin_rule`表插入`/menu/getMenu`接口后不提示没有权限了，但是没有返回数据，登录不上后台，作者确定按照现在的`readme`跟视频真的能部署成功吗？我是部署不起来。

**Comment by madneal** [comment]
@yggo 5.7.26 版本可能是过低的，我用的是 8.0 以上的版本，关于数据库权限你可以查看一下数据是否同步成功

```
	{PType: "p", V0: "888", V1: "/menu/getMenu", V2: "POST"},
```

**Comment by madneal** [comment]
今天把最新的 v1.0.2 版本发布，没有遇到任何问题，如果是数据库同步失败的话，可能是数据库版本比较低的原因，稍后我会更新发布视频

**Comment by madneal** [comment]
https://www.bilibili.com/video/BV1Zx4y1G7FX/
