### ISSUE TITLE
删库

### ISSUE THREAD

**Issue by scopion** [madneal/gshark#130]
之前配好了
机器崩溃重启了一次

再登录自动跳转初始化页面
不让登录
一直告诉第一次
然后初始化把之前的数据库删了

**Comment by scopion** [comment]
是否是初次登录是哪里判断的？

**Comment by scopion** [comment]
![image](https://user-images.githubusercontent.com/27413591/201600553-179ada02-2fff-45ac-8a18-c98ab7642330.png)
这里重启后，加载数据错误。我把这一条删了。后边没有报这个错了

**Comment by scopion** [comment]
![image](https://user-images.githubusercontent.com/27413591/201601107-02917b72-1a2e-40f4-80e1-b9a3e34f6ac4.png)
重启后第一次报错，我把这条数据处理了，后面没有报错了。

**Comment by scopion** [comment]
![image](https://user-images.githubusercontent.com/27413591/201601390-460b3522-95aa-436b-ae38-f98b938cfdad.png)
然后就是初始化删库。删库完了创建还没成功。

**Comment by madneal** [comment]
第一张截图是因为你的 url 过长，调整 url 数据库字段长度即可；
系统并没有删除你的数据库，可能是你的 `config.yaml` 文件有问题，检查一下，看看你的数据库配置是否正确

**Comment by scopion** [comment]
是否是初次登录是哪里判断的？

**Comment by scopion** [comment]
1.url问题，数据库的设置 跟你代码的设置是 匹配的。但是造成一个问题，scan的时候发现过长的url入不了库，改数据库字段长度的话，在web页面也无法显示。因为程序代码无法处理过长的url。这个BUG我无所谓

**Comment by scopion** [comment]
2.我比较关心，初次登录的判断是从哪里判断的？服务器崩溃重启的时候，web，scan，数据库都已经启动了。config.yaml 没改动，服务器重启，服务重启，我也没有动机去改配置文件。但是登录web一直强制跳转初始化页面，初始化过程会操作配置文件及数据库，数据库就是这么没的。

**Comment by scopion** [comment]
我加你微信了，你复现不了请联系我。

**Comment by madneal** [comment]
```
func CheckDB(c *gin.Context) {
	if global.GVA_DB != nil {
		global.GVA_LOG.Info("数据库无需初始化")
		response.OkWithDetailed(gin.H{
			"needInit": false,
		}, "数据库无需初始化", c)
		return
	} else {
		global.GVA_LOG.Info("前往初始化数据库")
		response.OkWithDetailed(gin.H{
			"needInit": true,
		}, "前往初始化数据库", c)
		return
	}
}
```
你这个我必然是复现不了的

**Comment by scopion** [comment]
![image](https://user-images.githubusercontent.com/27413591/202334193-9f7bfc90-12c7-403c-b41d-fbeb18bc2237.png)
这张日志，过程整理如下：
前情提要：初次安装完成，web跟scan都启动成功，服务正常运行。scan出现过搜索结果过长，无法入库的问题。于是我将数据库里url字段类型改成了longtext，scan可以正常入库了。过长的纪录是第988条。
问题提要：服务器崩溃重启，我重启了数据库，web，scan。web启动后，连接数据库，格式化数据。到了988的时候，因为过长无法格式化。web的后续能否正常运行，未知。scan一直正常运行。

**Comment by scopion** [comment]
![image](https://user-images.githubusercontent.com/27413591/202336114-db23aad2-12ca-4c52-a4dc-ad94bbd48974.png)
这张日志，过程整理如下：
前情提要：初次安装完成，web跟scan都启动成功，服务正常运行。scan出现过搜索结果过长，无法入库的问题。于是我将数据库里url字段类型改成了longtext，scan可以正常入库了。过长的纪录是第988条。
问题提要：服务器崩溃重启，我重启了数据库，web，scan。web启动后，连接数据库，格式化数据。到了988的时候，因为过长无法格式化。web的后续情况，未知。scan一直正常运行。

**Comment by scopion** [comment]
页面表现：
web页面一直固定在initial页面，要求初始化数据库。于是我将url改为login，但是它自动跳转initial页面。一直要求我初始化数据库。
个人操作：
这时候我的库还在。看了眼日志发现上面日志提示，于是我在库中把988这一行删掉了。
然后去web页面，它依然要求我初始化数据库。
这里就明显异常，但是我的库是有的。于是我以为在配置文件或其他地方有个配置（类似于0，1）设置程序是否为初次登录。
于是找配置文件，没找到。然后把yaml删了，用模板又建了一个。

**Comment by scopion** [comment]
![image](https://user-images.githubusercontent.com/27413591/202336729-d90aafaa-32bc-4b1e-b4b2-3c743e16c739.png)
然后继续到页面操作，但是信息填错了，于是有了 'root'@'localhost' ，这两条报警。**这期间，数据库也还在，scan是正常运行的。**
然后我使用对的数据库信息，在web页面初始化，然后web就**把以前的库删了，创建新库，但是没有成功**。这里我不知道为啥不成功。
web页面在初始化后，成功跳转到登录页面，然后登录。但是因为没有库，报了  **非法访问**  这个日志。
然后紧接着，scan程序因为找不到库，也报错了。

**Comment by scopion** [comment]
今天看了你的回复，我大概知道问题在哪了。
是否初次登录是代码判断的，没用配置项判断。

于是有以下猜测：
**web程序，格式化数据，遇到库中 格式不了的数据的时候，就停止了，并未完成整个操作。于是它以为我是刚安装的程序。一直给我强制跳转初始化页面。**

我删除988这条数据是对的，此时数据库中的数据都是可以正常使用的。
然后我应该kill 掉 web程序，重启一下它。就应该可以正常用了。

但是实际操作中，我并没有重启，于是整个过程就强制按照初次登录的步骤往下走，于是库就没了。
