### ISSUE TITLE
替换域名的形式

### ISSUE THREAD

**Issue by qing-root** [madneal/gshark#132]
# 需求 多个规则以后替换可否优化呢，比如我现在对a.com加了三条规则，扫描后又需要对b.com扫描同样的规则：
![image](https://user-images.githubusercontent.com/30001685/204140940-f15ae8a2-2224-41f7-87c8-57db71881aad.png)

这个时候我只有手动去编译每条规则替换域名。

师傅可否优化成一键替换域名这样的功能呢 : )

**Comment by madneal** [comment]
不太理解你的意思，你的规则是 `a.com keyword1` `a.comkeyword2` 想换成 `b.com keyword2` `b.com keyword1`，目前没有很好的实现形式，因为这就是不同的规则内容了

**Comment by qing-root** [comment]
> 

是的 大致就是这个效果 如果有以后优化规则编写的话师傅可以考虑一下
