### ISSUE TITLE
无法读取到gitlab规则

### ISSUE THREAD

**Issue by 869141534** [madneal/gshark#133]
规则管理处填写了gitlab对应的规则，但是执行命令无法扫描到规则，github可以
![1](https://user-images.githubusercontent.com/67504716/209782544-17a316e6-eaf7-4959-9e7a-930db1bd8a78.png)
![3](https://user-images.githubusercontent.com/67504716/209782727-c15baa45-71a4-410a-9018-71dbedbb36f6.png)
![2](https://user-images.githubusercontent.com/67504716/209782392-22ceb742-f71e-41da-856d-915ccf5c1c90.png)

**Comment by madneal** [comment]
gitlab 没加 github 那样的 log 语句而已，只不过是没扫描到结果，规则应该是有的
