### ISSUE TITLE
[Default Permission Error]

### ISSUE THREAD

**Issue by Scyllaly** [madneal/gshark#137]
**Describe the bug**
When i try to disable a rule, it display some error as below:
1.<img width="612" alt="image" src="https://user-images.githubusercontent.com/30641000/213181651-43fc4da9-b622-42cf-be8f-8b31f4fdd122.png">

i think,  the rule will be automatically disabled when the scan action is completed, but actually not.

2. The "Change" button can not click!
<img width="362" alt="image" src="https://user-images.githubusercontent.com/30641000/213181910-6660a3e5-bac1-4068-8fed-a98ce29cce6f.png">

**Comment by madneal** [comment]
execute sql
```
insert into casbin_rule (p_type, v0, v1, v2) values ('p', 888, '/rule/switchRuleStatus', 'POST');
```
