### ISSUE TITLE
大佬有没有考虑加个直接忽略仓库的功能

### ISSUE THREAD

**Issue by Cyber-Chaser** [madneal/gshark#138]
有些仓库被命中的文件内容非常多，但是实际上都是无关项，批量忽略还是稍微麻烦了点。或者有什么其他方式可以应对这种场景的

**Comment by Cyber-Chaser** [comment]
另外规则管理页面的变更按钮会报错
<img width="570" alt="image" src="https://user-images.githubusercontent.com/37996512/215302430-98ffbcbf-395f-4675-88fa-3f8b8b1207f7.png">
/api/rule/findRule获取内容没问题，但是前端报错了无法编辑

**Comment by madneal** [comment]
你忽略一条结果就自动忽略了整个仓库，第二个错误新版本应该已经修复了。
