### ISSUE TITLE
配置到最后一步，提示非法访问

### ISSUE THREAD

**Issue by huangzexinmingyqf** [madneal/gshark#139]
![image](https://user-images.githubusercontent.com/81756571/217024505-7a6e0e98-2da5-4623-af7c-b2182518bf85.png)
![image](https://user-images.githubusercontent.com/81756571/217024906-c565b407-45e5-40e3-8b78-a6ed5ef802d5.png)

**Comment by huangzexinmingyqf** [comment]
这里使用的是window 安装，config-temp.yaml直接改成config.yaml
![image](https://user-images.githubusercontent.com/81756571/217025266-4c2a3486-e205-435a-b57b-53994d627ee2.png)

**Comment by madneal** [comment]
使用最新版本，这个数据库创建失败了

**Comment by huangzexinmingyqf** [comment]
已解决，问题出现的原因是用了旧版本，换成新版本就成功了
![image](https://user-images.githubusercontent.com/81756571/217116125-f46c7cf9-8fb1-4ad8-bbff-0fa942d2e2ef.png)
