### ISSUE TITLE
规则管理-无法更改规则状态

### ISSUE THREAD

**Issue by Scyllaly** [madneal/gshark#142]
**Describe the bug**
无法更改规则的状态为true，改为false可以

报错如下：
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/30641000/218678378-ef828070-45fe-4caf-994e-d4dcc90ba6e1.png">

**Comment by VANCIO** [comment]
还是存在

**Comment by VANCIO** [comment]
最新版本还是存在
