### ISSUE TITLE
能否添加一个过滤功能，过滤.json之类的数据文件

### ISSUE THREAD

**Issue by Scyllaly** [madneal/gshark#144]
在添加关键词时，会通过github的api拉取回来搜索结果，但是能否在添加时或者系统配置里默认忽略.json这种文件类型的文件（即便它已经存储到系统里了，但是默认被标记为忽略）

**Comment by Scyllaly** [comment]
出了.json 还有.csv

**Comment by Scyllaly** [comment]
抱歉，我看到了有这个功能了，我试用一下

**Comment by madneal** [comment]
<img width="753" alt="image" src="https://user-images.githubusercontent.com/12164075/218960884-38b96cca-706e-4275-bd91-740935204c2e.png">

可以过滤的，但是不会存储

**Comment by Scyllaly** [comment]
<img width="880" alt="image" src="https://user-images.githubusercontent.com/30641000/218971539-9b421999-88f8-4f55-aa40-8350369aaf25.png">

**Comment by Scyllaly** [comment]
<img width="771" alt="image" src="https://user-images.githubusercontent.com/30641000/218972080-7f87a721-92df-491c-bb45-b515f2dc0577.png">

**Comment by madneal** [comment]
```
insert into sys_apis (created_at, updated_at, deleted_at, path, description, api_group, method) VALUES
    (current_timestamp, current_timestamp, null, '/searchResult/startSecFilterTask', '开始二次过滤任务', 'searchResult', 'POST');
insert into casbin_rule (p_type, v0, v1, v2) values ('p', 888, '/searchResult/startSecFilterTask', 'POST');

insert into sys_apis (created_at, updated_at, deleted_at, path, description, api_group, method) VALUES
    (current_timestamp, current_timestamp, null, '/searchResult/getTaskStatus', '查询任务状态', 'searchResult', 'GET');
insert into casbin_rule (p_type, v0, v1, v2) values ('p', 888, '/searchResult/getTaskStatus', 'GET');
```

**Comment by Scyllaly** [comment]
逻辑是不是错了，当我先爬取了数据，然后再添加过滤规则里的二次过滤"json,csv"， 执行“启动二次过滤”后，所有记录status都变成了2，这个过滤规则的逻辑不应该是当我点了启动二次过滤时，程序根据 url 去判断是否为.json 或者 .csv结尾的，如果是则忽略吗？

**Comment by madneal** [comment]
二次过滤和这个后缀没有关系的，二次过滤只针对二级关键词，不针对后缀
