### ISSUE TITLE
'/swagger/*any' in new path '/swagger/*any' conflicts with existing wildcard '/*filepath' in existing prefix '/*filepath'

### ISSUE THREAD

**Issue by tianxiabingmadadudu** [madneal/gshark#150]
[GIN-debug] GET    /swagger/*any             --> github.com/swaggo/gin-swagger.CustomWrapHandler.func1 (3 handlers)
panic: '/swagger/*any' in new path '/swagger/*any' conflicts with existing wildcard '/*filepath' in existing prefix '/*filepath'

goroutine 1 [running]:
github.com/gin-gonic/gin.(*node).addRoute(0x10f75b1?, {0xc00077df20, 0xd}, {0xc00065cd80, 0x3, 0x3})
        /Users/tianxiabingmadadudu/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/tree.go:247 +0xbea
github.com/gin-gonic/gin.(*Engine).addRoute(0xc0000a5d40, {0x10f75b1, 0x3}, {0xc00077df20, 0xd}, {0xc00065cd80, 0x3, 0x3})
        /Users/tianxiabingmadadudu/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:335 +0x226
github.com/gin-gonic/gin.(*RouterGroup).handle(0xc0000a5d40, {0x10f75b1, 0x3}, {0x1109e26?, 0x0?}, {0xc000011c80, 0x1, 0x1?})
        /Users/tianxiabingmadadudu/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/routergroup.go:89 +0x145
github.com/gin-gonic/gin.(*RouterGroup).GET(...)
        /Users/tianxiabingmadadudu/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/routergroup.go:117
github.com/madneal/gshark/initialize.Routers()
        /Applications/Go/server/initialize/router.go:25 +0x12d
github.com/madneal/gshark/core.RunWindowsServer(0xc000764e80?)
        /Applications/Go/server/core/server.go:21 +0x39
github.com/urfave/cli/v2.(*Command).Run(0x1bf1c80, 0xc000764e40)
        /Users/tianxiabingmadadudu/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x5bb
github.com/urfave/cli/v2.(*App).RunContext(0xc0000a5ba0, {0x1303b78?, 0xc0000380c0}, {0xc000032060, 0x2, 0x2})
        /Users/tianxiabingmadadudu/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0xb48
github.com/urfave/cli/v2.(*App).Run(...)
        /Users/tianxiabingmadadudu/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
        /Applications/Go/server/main.go:41 +0x430

**Comment by tianxiabingmadadudu** [comment]
it run on linux os

**Comment by tianxiabingmadadudu** [comment]
build on mac

**Comment by madneal** [comment]
plz describle it with full context, I cannot understand what's your meaning? How do you triger the error

**Comment by tianxiabingmadadudu** [comment]
> plz describle it with full context, I cannot understand what's your meaning? How do you triger the error

I mean, in a Mac environment, compiling a Linux program and running it on Linux reported a routing conflict error, but in a Mac environment, it works normally.

**Comment by madneal** [comment]
For mac, you should compile as darwin ow. For linux, you should use linux version. You should not use a mac version compiled program on linux.
