### ISSUE TITLE
初始化问题版本1.1.4

### ISSUE THREAD

**Issue by fdrong** [madneal/gshark#155]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
sql.md里面没有初始化用户和权限，登陆有问题，启动之前把config.yaml的数据库配置修改好了，启动表都建立好了，但是里面sys_users没有任何数据，登陆失败，能否把默认用户初始化脚本也放在启动里面

**Comment by madneal** [comment]
sql.md 只是后来一些新增 feature 涉及的数据库改动，初始化的已经会同步数据了，如果 sys_users 没有任何数据，证明初始化失败了。一般可能的问题是数据库版本导致的。
