### ISSUE TITLE
Specified key was too long;

### ISSUE THREAD

**Issue by bazhahei123** [madneal/gshark#157]
init 过程中，error 提示"err": "Error 1071: Specified key was too long; max key length is 1000 bytes"}
![图片](https://github.com/madneal/gshark/assets/43128559/5f691445-b23f-4cad-a4ea-eb304cd1c42f)
大佬们咋解决啊555

**Comment by bazhahei123** [comment]
感谢大佬

**Comment by Jadon-gem** [comment]
![image](https://github.com/madneal/gshark/assets/54278415/e3b42ab0-62d7-4ba4-bf8a-7ca2d05df276)
<img width="964" alt="image" src="https://github.com/madneal/gshark/assets/54278415/11241fbc-5723-450d-983c-06c202236095">
配置失败404 不清楚什么原因
