### ISSUE TITLE
部署失败

### ISSUE THREAD

**Issue by Jadon-gem** [madneal/gshark#158]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

您好部署失败该配置的已经配置好了但是还是无法启动
![image](https://github.com/madneal/gshark/assets/54278415/a9f9adef-8d62-407b-b645-2d20234538ef)

<img width="968" alt="image" src="https://github.com/madneal/gshark/assets/54278415/dba7bf17-a395-461a-bf1d-aa77ad73f5ac">

**Comment by madneal** [comment]
看看你的后台吧，大概率还是数据库的问题

**Comment by wangyuncong123** [comment]
> 看看你的后台吧，大概率还是数据库的问题
您好，我也是一样的问题，用centos部署的，后台没东西，就点什么都是404

**Comment by Jadon-gem** [comment]
> > 看看你的后台吧，大概率还是数据库的问题
> > 您好，我也是一样的问题，用centos部署的，后台没东西，就点什么都是404

数据库会是什么问题呢 也没问题啊
