### ISSUE TITLE
数据库显示无需初始化

### ISSUE THREAD

**Issue by JOHN-FROD** [madneal/gshark#162]
mac版本，mysql 8.1.0，手动创建gshark数据库
配置好config.yaml后访问没有跳转到初始化数据库页面
![image](https://github.com/madneal/gshark/assets/75994739/344334bb-21aa-46e5-bd51-7ff8e65d3396)
尝试直接访问初始化页面进行初始化，显示非法访问
![image](https://github.com/madneal/gshark/assets/75994739/1ea173d9-22cb-454a-bc23-e3c0220450b7)
查看数据库信息发现表是创建好了，但是没有数据

**Comment by madneal** [comment]
把数据库删掉，尝试重新初始化一下吧

**Comment by cyberyj** [comment]
> mac版本，mysql 8.1.0，手动创建gshark数据库 配置好config.yaml后访问没有跳转到初始化数据库页面 ![image](https://user-images.githubusercontent.com/75994739/258975417-344334bb-21aa-46e5-bd51-7ff8e65d3396.png) 尝试直接访问初始化页面进行初始化，显示非法访问 ![image](https://user-images.githubusercontent.com/75994739/258975791-1ea173d9-22cb-454a-bc23-e3c0220450b7.png) 查看数据库信息发现表是创建好了，但是没有数据

师傅你解决了吗？

**Comment by Yang2635** [comment]
同创建了数据库表，无数据。Linux、MySQL版本：8.0.27

**Comment by 0FuzzingQ** [comment]
一样的问题 请问解决了吗
