### ISSUE TITLE
gshark web启动失败，师傅麻烦解答一下

### ISSUE THREAD

**Issue by cyberyj** [madneal/gshark#163]
./gshark web
您正在使用config的默认值,config的路径为config.yaml
/home/yingjun/gshark_linux_amd64 <nil>
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /uploads/file/*filepath   --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (3 handlers)
[GIN-debug] HEAD   /uploads/file/*filepath   --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (3 handlers)
[GShark]2023/08/11-17:13:39	info	use middleware logger
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x8bbdf8]

goroutine 8 [running]:
gorm.io/gorm.(*DB).getInstance(0x0?)
	/home/runner/go/pkg/mod/gorm.io/gorm@v1.20.9/gorm.go:306 +0x18
gorm.io/gorm.(*DB).Table(0x0?, {0xf7dc91, 0x4}, {0x0, 0x0, 0x0})
	/home/runner/go/pkg/mod/gorm.io/gorm@v1.20.9/chainable_api.go:48 +0x3c
github.com/madneal/gshark/service.CheckTaskStatus({0xf8006b, 0x6})
	/home/runner/work/gshark/gshark/server/service/task.go:42 +0x45
github.com/madneal/gshark/search.ScanTask()
	/home/runner/work/gshark/gshark/server/search/scan.go:17 +0x3a
created by main.main
	/home/runner/work/gshark/gshark/server/main.go:19 +0x119
root@iZ2ze658uktnorp1kgmuyrZ:/home/yingjun/gshark_linux_amd64#

**Comment by madneal** [comment]
./gshark

**Comment by cyberyj** [comment]
> 这个看着是数据库的问题，数据库的配置都有了吗
数据库MYSQL8.0装了，但是config.yaml里面没有配置，我看师傅视频里面也没有设置什么，直接就启动了。望师傅解答

**Comment by madneal** [comment]
需要按照你的数据库参数配置
