### ISSUE TITLE
数据库显示无需初始化。

### ISSUE THREAD

**Issue by cyberyj** [madneal/gshark#164]
师傅，创建好数据库后，提示无需初始化，无法进入系统

数据库版本如下:
mysql  Ver 8.0.34 for Linux on x86_64 (MySQL Community Server - GPL)

**Comment by cyberyj** [comment]
v1.1.4版本无任何问题，初始化成功！

**Comment by cyberyj** [comment]
最新版v1.2.0有问题，我使用v1.1.4初始化数据库，然后使用再启动的v1.2.0

**Comment by hackneal** [comment]
有具体的错误嘛

**Comment by madneal** [comment]
什么错误

**Comment by madneal** [comment]
自己看看 user 表有没有数据，gshark/gshark 默认用户名密码

**Comment by cyberyj** [comment]
> 最新版本应该已经修复初始化逻辑的问题
感谢师傅
