### ISSUE TITLE
1.2.0启动失败

### ISSUE THREAD

**Issue by buhonghao** [madneal/gshark#165]
root@Ubuntu:/var/www/html# ./gshark scan
您正在使用config的默认值,config的路径为config.yaml
/var/www/html <nil>
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /uploads/file/*filepath   --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (3 handlers)
[GIN-debug] HEAD   /uploads/file/*filepath   --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (3 handlers)
[GShark]2023/08/19-16:11:19     info    use middleware logger
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x8bbdf8]

goroutine 9 [running]:
gorm.io/gorm.(*DB).getInstance(0x0?)
        /home/runner/go/pkg/mod/gorm.io/gorm@v1.20.9/gorm.go:306 +0x18
gorm.io/gorm.(*DB).Table(0x0?, {0xf7dc91, 0x4}, {0x0, 0x0, 0x0})
        /home/runner/go/pkg/mod/gorm.io/gorm@v1.20.9/chainable_api.go:48 +0x3c
github.com/madneal/gshark/service.CheckTaskStatus({0xf8006b, 0x6})
        /home/runner/work/gshark/gshark/server/service/task.go:42 +0x45
github.com/madneal/gshark/search.ScanTask()
        /home/runner/work/gshark/gshark/server/search/scan.go:17 +0x3a
created by main.main
        /home/runner/work/gshark/gshark/server/main.go:19 +0x119

测试了Ubuntu和Windows启动都是报上面的错，换1.1.4版本启动正常。

**Comment by madneal** [comment]
config.yaml 数据库配置了吗

**Comment by charis3306** [comment]
> config.yaml 数据库配置了吗

如何配置，这作者也不说。
这样吗？
![image](https://github.com/madneal/gshark/assets/84823804/a283ea18-a5b3-4fdb-8150-477959a2b653)

**Comment by madneal** [comment]
你自己的数据库账户密码还要我教你怎么配？？？
