### ISSUE TITLE
太难启动了我是小丑。

### ISSUE THREAD

**Issue by charis3306** [madneal/gshark#167]
** 问题一
### config.yaml 如何配置的。
** 数据库版本
![image](https://github.com/madneal/gshark/assets/84823804/051af339-419b-40e5-bfee-198772284e30)
** 按照配置文件创建数据库
![image](https://github.com/madneal/gshark/assets/84823804/2b9521ef-f0c9-45d6-a7d5-6376122b2336)

** nginx 这里省略配置没有问题
** 启动后端web子命令

![image](https://github.com/madneal/gshark/assets/84823804/3504e5e2-3f64-4bb7-af5d-dded3fa1103d)

![image](https://github.com/madneal/gshark/assets/84823804/db283f4e-9150-4aeb-b99b-b5dd688c63cf)

我就想知道你们是如何配置的！！！！！！！！！！！！！！！！！！！！！

**Comment by madneal** [comment]
https://cloud.tencent.com/developer/article/1005696
