### ISSUE TITLE
web页面自动跳过init，服务提示 数据库无需初始化问题

### ISSUE THREAD

**Issue by beijing-university** [madneal/gshark#170]
访问时直接进入登录了，不像视频中会跳转到init，且gshark/gshark无法登录，手动跳转到init提示非法访问
![image](https://github.com/madneal/gshark/assets/36041172/ab907a30-92b8-445f-b56a-30f7096b6953)

![image](https://github.com/madneal/gshark/assets/36041172/7f4bc652-a7ab-4c3c-a82d-a30d7f0f2316)
![image](https://github.com/madneal/gshark/assets/36041172/f7de2767-2c87-4749-8648-ca03ac3c65f5)

数据库为phpstudy，修改过mysql的索引引擎为innodb，无其他操作，数据库登录上去后为，数据都为空
![image](https://github.com/madneal/gshark/assets/36041172/0db1266a-0d71-4b73-b4c8-55494707b7c0)

**Comment by beijing-university** [comment]
安装过程中遇到的，nginx1.2.4，没有修改配置，
![image](https://github.com/madneal/gshark/assets/36041172/06c5af06-c5b1-4e18-809c-3bffc5f3c2b3)

**Comment by madneal** [comment]
https://github.com/madneal/gshark/releases/tag/v1.2.2

**Comment by madneal** [comment]
最新版本已经修复
