### ISSUE TITLE
gshark scan扫描报错

### ISSUE THREAD

**Issue by guanhd** [madneal/gshark#171]
用的是v0.7版本，规则配置后，使用gshark scan扫描报错：
[GShark]2023/10/27 - 07:34:02.637       info    Github scan with the query:     {"github": "spring +in:file"}
[GShark]2023/10/27 - 07:34:49.356       error   Search error    {"github search error": "GET https://api.github.com/search/code?q=spring++in:file+-extension:.md+fork:false&order=desc&per_page=100&sort=indexed: 422 ERROR_TYPE_QUERY_PARSING_FATAL unable to parse query! []"}

**Comment by madneal** [comment]
这个是你的搜索语法问题，和 gshark 无关
