### ISSUE TITLE
您好，大佬，使用v1.2.2，执行scan的时候报错问题

### ISSUE THREAD

**Issue by suixingteng** [madneal/gshark#176]
在执行./gshark web之后，再去执行./gshark scan会报错
报错信息：
2023/11/17 16:34:47 net.Listen error: listen tcp :8888: bind: address already in use
[GShark]2023/11/17-16:34:47     error   net.Listen error: listen tcp :8888: bind: address already in use
请问是我使用的有问题吗？

**Comment by madneal** [comment]
这个端口被占用了啊

**Comment by suixingteng** [comment]
gshark web 和gshark scan两个同时开启会造成端口冲突，那使用的时候需要同时开启吗？

**Comment by madneal** [comment]
现在不需要起两个服务了啊，更新过介绍了啊

**Comment by suixingteng** [comment]
大佬，再打扰您一下，scan服务已经起来了，配置了规则，但是等了好久并没有扫描结果。
![image](https://github.com/madneal/gshark/assets/54239162/868d1ad4-9b30-444f-bc8e-15f40a5d1877)
![image](https://github.com/madneal/gshark/assets/54239162/0d133985-eaeb-4bbd-bae3-2f2517e8968b)
![image](https://github.com/madneal/gshark/assets/54239162/480a442e-4651-4212-abfa-da2fd0ddd186)
![image](https://github.com/madneal/gshark/assets/54239162/ad840b2c-f035-4182-bd69-7e63b177b583)
请问是我配置方面有什么问题吗？
