### ISSUE TITLE
scan没有进行扫描

### ISSUE THREAD

**Issue by suixingteng** [madneal/gshark#177]

**Comment by suixingteng** [comment]
大佬，再打扰您一下，scan服务已经起来了，配置了规则，但是等了好久并没有扫描结果。
![image](https://github.com/madneal/gshark/assets/54239162/19e7f942-d5d7-4bd0-affe-893f53c7bee4)
![image](https://github.com/madneal/gshark/assets/54239162/31dc57e3-650a-4659-9246-db70d2802d0c)
![image](https://github.com/madneal/gshark/assets/54239162/76c65d2c-6071-4f88-ab6c-9baef4c3024d)
![image](https://github.com/madneal/gshark/assets/54239162/5608d7d5-3148-46b2-9998-945374306c6a)
请问是我配置方面有什么问题吗？我应该如何去排错？

**Comment by madneal** [comment]
把你的 token 掩码掉，泄露了，服务重新启动一次

**Comment by suixingteng** [comment]
好的，我重启了服务。但是他还是没有去请求api

**Comment by madneal** [comment]
关注一下控制台吧，应该有扫描的日志

**Comment by suixingteng** [comment]
大佬，我想加一下您的微信，介绍的微信没搜索到人，可以吗？

**Comment by suixingteng** [comment]
大佬，等了一段时间，没有进行扫描。请问我是设置方面出现了问题吗？
控制台信息：
root@user-VMware-Virtual-Platform:~/gshark_linux_amd64# ./gshark scan
鎮ㄦ鍦ㄤ娇鐢╟onfig鐨勯粯璁ゅ€�,config鐨勮矾寰勪负config.yaml
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /uploads/file/*filepath   --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (3 handlers)
[GIN-debug] HEAD   /uploads/file/*filepath   --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (3 handlers)
[GShark]2023/11/19-20:26:42	info	use middleware logger
[GIN-debug] GET    /swagger/*any             --> github.com/swaggo/gin-swagger.CustomWrapHandler.func1 (3 handlers)
[GShark]2023/11/19-20:26:42	info	register swagger handler
[GIN-debug] POST   /base/login               --> github.com/madneal/gshark/api.Login (4 handlers)
[GIN-debug] POST   /base/captcha             --> github.com/madneal/gshark/api.Captcha (4 handlers)
[GIN-debug] POST   /init/initdb              --> github.com/madneal/gshark/api.InitDB (3 handlers)
[GIN-debug] POST   /init/checkdb             --> github.com/madneal/gshark/api.CheckDB (3 handlers)
[GIN-debug] POST   /api/createApi            --> github.com/madneal/gshark/api.CreateApi (6 handlers)
[GIN-debug] POST   /api/deleteApi            --> github.com/madneal/gshark/api.DeleteApi (6 handlers)
[GIN-debug] POST   /api/getApiList           --> github.com/madneal/gshark/api.GetApiList (6 handlers)
[GIN-debug] POST   /api/getApiById           --> github.com/madneal/gshark/api.GetApiById (6 handlers)
[GIN-debug] POST   /api/updateApi            --> github.com/madneal/gshark/api.UpdateApi (6 handlers)
[GIN-debug] POST   /api/getAllApis           --> github.com/madneal/gshark/api.GetAllApis (6 handlers)
[GIN-debug] POST   /jwt/jsonInBlacklist      --> github.com/madneal/gshark/api.JsonInBlacklist (6 handlers)
[GIN-debug] POST   /user/register            --> github.com/madneal/gshark/api.Register (6 handlers)
[GIN-debug] POST   /user/changePassword      --> github.com/madneal/gshark/api.ChangePassword (6 handlers)
[GIN-debug] POST   /user/getUserList         --> github.com/madneal/gshark/api.GetUserList (6 handlers)
[GIN-debug] POST   /user/setUserAuthority    --> github.com/madneal/gshark/api.SetUserAuthority (6 handlers)
[GIN-debug] DELETE /user/deleteUser          --> github.com/madneal/gshark/api.DeleteUser (6 handlers)
[GIN-debug] PUT    /user/setUserInfo         --> github.com/madneal/gshark/api.SetUserInfo (6 handlers)
[GIN-debug] POST   /menu/getMenu             --> github.com/madneal/gshark/api.GetMenu (6 handlers)
[GIN-debug] POST   /menu/getMenuList         --> github.com/madneal/gshark/api.GetMenuList (6 handlers)
[GIN-debug] POST   /menu/addBaseMenu         --> github.com/madneal/gshark/api.AddBaseMenu (6 handlers)
[GIN-debug] POST   /menu/getBaseMenuTree     --> github.com/madneal/gshark/api.GetBaseMenuTree (6 handlers)
[GIN-debug] POST   /menu/addMenuAuthority    --> github.com/madneal/gshark/api.AddMenuAuthority (6 handlers)
[GIN-debug] POST   /menu/getMenuAuthority    --> github.com/madneal/gshark/api.GetMenuAuthority (6 handlers)
[GIN-debug] POST   /menu/deleteBaseMenu      --> github.com/madneal/gshark/api.DeleteBaseMenu (6 handlers)
[GIN-debug] POST   /menu/updateBaseMenu      --> github.com/madneal/gshark/api.UpdateBaseMenu (6 handlers)
[GIN-debug] POST   /menu/getBaseMenuById     --> github.com/madneal/gshark/api.GetBaseMenuById (6 handlers)
[GIN-debug] POST   /system/getSystemConfig   --> github.com/madneal/gshark/api.GetSystemConfig (6 handlers)
[GIN-debug] POST   /system/setSystemConfig   --> github.com/madneal/gshark/api.SetSystemConfig (6 handlers)
[GIN-debug] POST   /system/getServerInfo     --> github.com/madneal/gshark/api.GetServerInfo (6 handlers)
[GIN-debug] POST   /system/reloadSystem      --> github.com/madneal/gshark/api.ReloadSystem (6 handlers)
[GIN-debug] POST   /casbin/updateCasbin      --> github.com/madneal/gshark/api.UpdateCasbin (6 handlers)
[GIN-debug] POST   /casbin/getPolicyPathByAuthorityId --> github.com/madneal/gshark/api.GetPolicyPathByAuthorityId (6 handlers)
[GIN-debug] POST   /autoCode/preview         --> github.com/madneal/gshark/api.PreviewTemp (5 handlers)
[GIN-debug] POST   /autoCode/createTemp      --> github.com/madneal/gshark/api.CreateTemp (5 handlers)
[GIN-debug] GET    /autoCode/getTables       --> github.com/madneal/gshark/api.GetTables (5 handlers)
[GIN-debug] GET    /autoCode/getDB           --> github.com/madneal/gshark/api.GetDB (5 handlers)
[GIN-debug] GET    /autoCode/getColumn       --> github.com/madneal/gshark/api.GetColumn (5 handlers)
[GIN-debug] POST   /authority/createAuthority --> github.com/madneal/gshark/api.CreateAuthority (6 handlers)
[GIN-debug] POST   /authority/deleteAuthority --> github.com/madneal/gshark/api.DeleteAuthority (6 handlers)
[GIN-debug] PUT    /authority/updateAuthority --> github.com/madneal/gshark/api.UpdateAuthority (6 handlers)
[GIN-debug] POST   /authority/copyAuthority  --> github.com/madneal/gshark/api.CopyAuthority (6 handlers)
[GIN-debug] POST   /authority/getAuthorityList --> github.com/madneal/gshark/api.GetAuthorityList (6 handlers)
[GIN-debug] POST   /authority/setDataAuthority --> github.com/madneal/gshark/api.SetDataAuthority (6 handlers)
[GIN-debug] POST   /sysDictionary/createSysDictionary --> github.com/madneal/gshark/api.CreateSysDictionary (6 handlers)
[GIN-debug] DELETE /sysDictionary/deleteSysDictionary --> github.com/madneal/gshark/api.DeleteSysDictionary (6 handlers)
[GIN-debug] PUT    /sysDictionary/updateSysDictionary --> github.com/madneal/gshark/api.UpdateSysDictionary (6 handlers)
[GIN-debug] GET    /sysDictionary/findSysDictionary --> github.com/madneal/gshark/api.FindSysDictionary (6 handlers)
[GIN-debug] GET    /sysDictionary/getSysDictionaryList --> github.com/madneal/gshark/api.GetSysDictionaryList (6 handlers)
[GIN-debug] POST   /sysOperationRecord/createSysOperationRecord --> github.com/madneal/gshark/api.CreateSysOperationRecord (6 handlers)
[GIN-debug] DELETE /sysOperationRecord/deleteSysOperationRecord --> github.com/madneal/gshark/api.DeleteSysOperationRecord (6 handlers)
[GIN-debug] DELETE /sysOperationRecord/deleteSysOperationRecordByIds --> github.com/madneal/gshark/api.DeleteSysOperationRecordByIds (6 handlers)
[GIN-debug] GET    /sysOperationRecord/findSysOperationRecord --> github.com/madneal/gshark/api.FindSysOperationRecord (6 handlers)
[GIN-debug] GET    /sysOperationRecord/getSysOperationRecordList --> github.com/madneal/gshark/api.GetSysOperationRecordList (6 handlers)
[GIN-debug] POST   /sysDictionaryDetail/createSysDictionaryDetail --> github.com/madneal/gshark/api.CreateSysDictionaryDetail (6 handlers)
[GIN-debug] DELETE /sysDictionaryDetail/deleteSysDictionaryDetail --> github.com/madneal/gshark/api.DeleteSysDictionaryDetail (6 handlers)
[GIN-debug] PUT    /sysDictionaryDetail/updateSysDictionaryDetail --> github.com/madneal/gshark/api.UpdateSysDictionaryDetail (6 handlers)
[GIN-debug] GET    /sysDictionaryDetail/findSysDictionaryDetail --> github.com/madneal/gshark/api.FindSysDictionaryDetail (6 handlers)
[GIN-debug] GET    /sysDictionaryDetail/getSysDictionaryDetailList --> github.com/madneal/gshark/api.GetSysDictionaryDetailList (6 handlers)
[GIN-debug] POST   /email/emailTest          --> github.com/madneal/gshark/api.EmailTest (6 handlers)
[GIN-debug] GET    /email/botTest            --> github.com/madneal/gshark/api.BotTest (6 handlers)
[GIN-debug] POST   /rule/createRule          --> github.com/madneal/gshark/api.CreateRule (6 handlers)
[GIN-debug] DELETE /rule/deleteRule          --> github.com/madneal/gshark/api.DeleteRule (6 handlers)
[GIN-debug] DELETE /rule/deleteRuleByIds     --> github.com/madneal/gshark/api.DeleteRuleByIds (6 handlers)
[GIN-debug] PUT    /rule/updateRule          --> github.com/madneal/gshark/api.UpdateRule (6 handlers)
[GIN-debug] GET    /rule/findRule            --> github.com/madneal/gshark/api.FindRule (6 handlers)
[GIN-debug] GET    /rule/getRuleList         --> github.com/madneal/gshark/api.GetRuleList (6 handlers)
[GIN-debug] POST   /rule/switchRuleStatus    --> github.com/madneal/gshark/api.SwitchRuleStatus (6 handlers)
[GIN-debug] POST   /rule/uploadRules         --> github.com/madneal/gshark/api.UploadRules (6 handlers)
[GIN-debug] POST   /token/createToken        --> github.com/madneal/gshark/api.CreateToken (6 handlers)
[GIN-debug] DELETE /token/deleteToken        --> github.com/madneal/gshark/api.DeleteToken (6 handlers)
[GIN-debug] DELETE /token/deleteTokenByIds   --> github.com/madneal/gshark/api.DeleteTokenByIds (6 handlers)
[GIN-debug] PUT    /token/updateToken        --> github.com/madneal/gshark/api.UpdateToken (6 handlers)
[GIN-debug] GET    /token/findToken          --> github.com/madneal/gshark/api.FindToken (6 handlers)
[GIN-debug] GET    /token/getTokenList       --> github.com/madneal/gshark/api.GetTokenList (6 handlers)
[GIN-debug] POST   /searchResult/createSearchResult --> github.com/madneal/gshark/api.CreateSearchResult (6 handlers)
[GIN-debug] DELETE /searchResult/deleteSearchResult --> github.com/madneal/gshark/api.DeleteSearchResult (6 handlers)
[GIN-debug] DELETE /searchResult/deleteSearchResultByIds --> github.com/madneal/gshark/api.DeleteSearchResultByIds (6 handlers)
[GIN-debug] POST   /searchResult/updateSearchResult --> github.com/madneal/gshark/api.UpdateSearchResult (6 handlers)
[GIN-debug] GET    /searchResult/findSearchResult --> github.com/madneal/gshark/api.FindSearchResult (6 handlers)
[GIN-debug] GET    /searchResult/getSearchResultList --> github.com/madneal/gshark/api.GetSearchResultList (6 handlers)
[GIN-debug] POST   /searchResult/updateSearchResultStatusByIds --> github.com/madneal/gshark/api.UpdateSearchResultByIds (6 handlers)
[GIN-debug] POST   /searchResult/startSecFilterTask --> github.com/madneal/gshark/api.StartSecFilterTask (6 handlers)
[GIN-debug] GET    /searchResult/getTaskStatus --> github.com/madneal/gshark/api.GetTaskStatus (6 handlers)
[GIN-debug] POST   /subdomain/createSubdomain --> github.com/madneal/gshark/api.CreateSubdomain (6 handlers)
[GIN-debug] DELETE /subdomain/deleteSubdomain --> github.com/madneal/gshark/api.DeleteSubdomain (6 handlers)
[GIN-debug] DELETE /subdomain/deleteSubdomainByIds --> github.com/madneal/gshark/api.DeleteSubdomainByIds (6 handlers)
[GIN-debug] PUT    /subdomain/updateSubdomain --> github.com/madneal/gshark/api.UpdateSubdomain (6 handlers)
[GIN-debug] GET    /subdomain/findSubdomain  --> github.com/madneal/gshark/api.FindSubdomain (6 handlers)
[GIN-debug] GET    /subdomain/getSubdomainList --> github.com/madneal/gshark/api.GetSubdomainList (6 handlers)
[GIN-debug] POST   /filter/createFilter      --> github.com/madneal/gshark/api.CreateFilter (6 handlers)
[GIN-debug] DELETE /filter/deleteFilter      --> github.com/madneal/gshark/api.DeleteFilter (6 handlers)
[GIN-debug] DELETE /filter/deleteFilterByIds --> github.com/madneal/gshark/api.DeleteFilterByIds (6 handlers)
[GIN-debug] PUT    /filter/updateFilter      --> github.com/madneal/gshark/api.UpdateFilter (6 handlers)
[GIN-debug] GET    /filter/findFilter        --> github.com/madneal/gshark/api.FindFilter (6 handlers)
[GIN-debug] GET    /filter/getFilterList     --> github.com/madneal/gshark/api.GetFilterList (6 handlers)
[GIN-debug] POST   /repo/createRepo          --> github.com/madneal/gshark/api.CreateRepo (6 handlers)
[GIN-debug] DELETE /repo/deleteRepo          --> github.com/madneal/gshark/api.DeleteRepo (6 handlers)
[GIN-debug] DELETE /repo/deleteRepoByIds     --> github.com/madneal/gshark/api.DeleteRepoByIds (6 handlers)
[GIN-debug] PUT    /repo/updateRepo          --> github.com/madneal/gshark/api.UpdateRepo (6 handlers)
[GIN-debug] GET    /repo/findRepo            --> github.com/madneal/gshark/api.FindRepo (6 handlers)
[GIN-debug] GET    /repo/getRepoList         --> github.com/madneal/gshark/api.GetRepoList (6 handlers)
[GIN-debug] GET    /task/getTaskList         --> github.com/madneal/gshark/api.GetTaskList (6 handlers)
[GIN-debug] POST   /task/createTask          --> github.com/madneal/gshark/api.CreateTask (6 handlers)
[GIN-debug] POST   /task/switchTaskStatus    --> github.com/madneal/gshark/api.SwitchTaskStatus (6 handlers)
[GShark]2023/11/19-20:26:42	info	router register success
[GShark]2023/11/19-20:26:42	info	server run success on 	{"address": ":8888"}
2023/11/19 20:26:42 3638 :8888
[GShark]2023/11/19-20:26:44	info	鏁版嵁搴撴棤闇€鍒濆鍖�
[GIN] 2023/11/19 - 20:26:44 | 200 |      169.19碌s |   192.168.128.1 | POST     "/init/checkdb"
[GIN] 2023/11/19 - 20:26:44 | 200 |   60.730884ms |   192.168.128.1 | POST     "/menu/getMenu"
[GIN] 2023/11/19 - 20:26:44 | 200 |   30.192232ms |   192.168.128.1 | GET      "/searchResult/getSearchResultList?page=1&pageSize=100"
[GIN] 2023/11/19 - 20:26:44 | 200 |   10.196238ms |   192.168.128.1 | GET      "/searchResult/getTaskStatus"
[GIN] 2023/11/19 - 20:26:46 | 200 |   19.236834ms |   192.168.128.1 | GET      "/rule/getRuleList?page=1&pageSize=100"
[GIN] 2023/11/19 - 20:26:47 | 200 |   14.663386ms |   192.168.128.1 | GET      "/token/getTokenList?page=1&pageSize=100"
[GIN] 2023/11/19 - 20:29:55 | 200 |   40.027297ms |   192.168.128.1 | GET      "/searchResult/getSearchResultList?page=1&pageSize=100"
[GIN] 2023/11/19 - 20:29:55 | 200 |   12.736799ms |   192.168.128.1 | GET      "/searchResult/getTaskStatus"
[GShark]2023/11/19-20:29:57	info	鏁版嵁搴撴棤闇€鍒濆鍖�
[GIN] 2023/11/19 - 20:29:57 | 200 |      90.002碌s |   192.168.128.1 | POST     "/init/checkdb"
[GIN] 2023/11/19 - 20:29:57 | 200 |   23.610937ms |   192.168.128.1 | POST     "/menu/getMenu"
[GIN] 2023/11/19 - 20:29:57 | 200 |   11.599863ms |   192.168.128.1 | GET      "/searchResult/getSearchResultList?page=1&pageSize=100"
[GIN] 2023/11/19 - 20:29:57 | 200 |   11.047637ms |   192.168.128.1 | GET      "/searchResult/getTaskStatus"
[GIN] 2023/11/19 - 20:30:06 | 200 |   10.722232ms |   192.168.128.1 | GET      "/token/getTokenList?page=1&pageSize=100"
[GIN] 2023/11/19 - 20:38:37 | 200 |   15.065758ms |   192.168.128.1 | GET      "/searchResult/getSearchResultList?page=1&pageSize=100"
[GIN] 2023/11/19 - 20:38:37 | 200 |   27.751951ms |   192.168.128.1 | GET      "/searchResult/getTaskStatus"


[GShark]2023/11/19-21:49:32	info	鏁版嵁搴撴棤闇€鍒濆鍖�
[GIN] 2023/11/19 - 21:49:32 | 200 |   19.192458ms |       127.0.0.1 | POST     "/init/checkdb"
[GIN] 2023/11/19 - 21:49:32 | 200 |    9.917841ms |       127.0.0.1 | POST     "/base/captcha"
[GIN] 2023/11/19 - 21:49:52 | 200 |   10.394034ms |       127.0.0.1 | POST     "/base/login"
[GIN] 2023/11/19 - 21:49:52 | 200 |   40.509044ms |       127.0.0.1 | POST     "/menu/getMenu"
[GIN] 2023/11/19 - 21:49:53 | 200 |   216.56014ms |       127.0.0.1 | POST     "/system/getServerInfo"
[GIN] 2023/11/19 - 21:49:55 | 200 |    20.21647ms |       127.0.0.1 | GET      "/searchResult/getSearchResultList?page=1&pageSize=100"
[GIN] 2023/11/19 - 21:49:55 | 200 |   46.938669ms |       127.0.0.1 | GET      "/searchResult/getTaskStatus"
[GIN] 2023/11/19 - 21:50:04 | 200 |   41.990259ms |       127.0.0.1 | GET      "/rule/getRuleList?page=1&pageSize=100"
[GIN] 2023/11/19 - 21:50:06 | 200 |   16.658334ms |       127.0.0.1 | GET      "/searchResult/getSearchResultList?page=1&pageSize=100"
[GIN] 2023/11/19 - 21:50:06 | 200 |   12.008688ms |       127.0.0.1 | GET      "/searchResult/getTaskStatus"
[GShark]2023/11/19-21:54:21	info	鏁版嵁搴撴棤闇€鍒濆鍖�
[GIN] 2023/11/19 - 21:54:21 | 200 |     548.529碌s |       127.0.0.1 | POST     "/init/checkdb"
[GIN] 2023/11/19 - 21:54:21 | 200 |    1.456125ms |       127.0.0.1 | POST     "/base/captcha

**Comment by madneal** [comment]
最新版本的修复了这个问题，应该是状态检查有bug，感谢反馈
