### ISSUE TITLE
[Error: Cannot find module './view/token/task.vue]

### ISSUE THREAD

**Issue by k3mlol** [madneal/gshark#179]
**Describe the bug**
after I add the task privilege to user, this user login agin, click the task tab, but html have an error, can't show the task page
I download the latest version, move the dist files to /var/www/html/

**Screenshots**
<img width="917" alt="image" src="https://github.com/madneal/gshark/assets/46588893/cc167faa-5953-446b-90b6-75971f4a7de2">

**Comment by madneal** [comment]
it should be `task/task.vue`. I have missed it in the sql.md. You can modify it by the sytem or modify the mysql table

**Comment by k3mlol** [comment]
thank you
