### ISSUE TITLE
没有scan命令了吗

### ISSUE THREAD

**Issue by q99266** [madneal/gshark#181]
![1](https://github.com/madneal/gshark/assets/49788237/1c006a9f-0716-4364-b9f7-d04c698b2f12)

**Comment by madneal** [comment]
没有了，scan 通过 web 创建任务

**Comment by VANCIO** [comment]
> 没有了，scan 通过 web 创建任务

如何查看任务的执行状态呢

**Comment by madneal** [comment]
web 界面有，但只有启用和禁用两个状态
