### ISSUE TITLE
请问如何为gshark对github的探测请求包配置自定义代理？

### ISSUE THREAD

**Issue by 1KuuhaKu1** [madneal/gshark#183]
首先很感谢作者的开源分享，但在gshark的使用过程中我发现我并不能自定义代理，因为我在中国访问Github稳定性差的问题，使我担心gshark的访问流量会不会丢失。

所以请问有没有办法让用户增添代理规则？请作者指教。

**Comment by madneal** [comment]
目前已经在最新版本中支持了系统的代理，参考 https://github.com/madneal/gshark/issues/120
