### ISSUE TITLE
docker构建失败

### ISSUE THREAD

**Issue by cx9208** [madneal/gshark#191]
```
go: downloading gopkg.in/fsnotify.v1 v1.4.7
go: downloading golang.org/x/mod v0.8.0
# github.com/madneal/gshark/api
api/sys_captcha.go:19:22: assignment mismatch: 3 variables but cp.Generate returns 4 values
ERROR: Service 'server' failed to build: The command '/bin/sh -c go env -w GO111MODULE=on     && go env -w GOPROXY=https://goproxy.cn,direct     && go env -w CGO_ENABLED=0     && go env     && go mod tidy     && go build -o server .' returned a non-zero code: 2
```

**Comment by madneal** [comment]
无法复现

**Comment by dead5nd** [comment]
修改server/go.mod中base64Captcha的版本为1.3.4再试试

**Comment by madneal** [comment]
https://github.com/madneal/gshark/issues/192 他好像是和你一样的问题，不可能是项目中依赖的版本问题

**Comment by jesse-zhangh** [comment]
同样的问题
`go: downloading github.com/klauspost/cpuid/v2 v2.2.4
go: downloading gopkg.in/fsnotify.v1 v1.4.7
go: downloading golang.org/x/mod v0.8.0
# github.com/madneal/gshark/api
api/sys_captcha.go:19:22: assignment mismatch: 3 variables but cp.Generate returns 4 values
The command '/bin/sh -c go env -w GO111MODULE=on     && go env -w GOPROXY=https://goproxy.cn,direct     && go env -w CGO_ENABLED=0     && go env     && go mod tidy     && go build -o server .' returned a non-zero code: 2
ERROR: Service 'server' failed to build : Build failed`

**Comment by jesse-zhangh** [comment]
OS 
Ubuntu22.04

**Comment by jesse-zhangh** [comment]
@dead5nd 谢谢，修改server/go.mod中base64Captcha的版本为1.3.4，可以构建成功
