### ISSUE TITLE
不进行扫描

### ISSUE THREAD

**Issue by dead5nd** [madneal/gshark#193]
任务管理
![image](https://github.com/madneal/gshark/assets/29460919/767b648f-c491-4315-b07f-6143d02bb411)
token也是可以使用
![image](https://github.com/madneal/gshark/assets/29460919/91d02991-4824-47f7-8833-f5bc94f9cf3c)
规则也有
![image](https://github.com/madneal/gshark/assets/29460919/5463b390-739c-438c-b907-4c89745d2e0d)
怎么不进行扫描啊

**Comment by madneal** [comment]
初次添加的时候需要重启下服务

**Comment by jesse-zhangh** [comment]
> 初次添加的时候需要重启下服务

docker compose 部署，应该重启哪个docker中的什么服务呢？

**Comment by madneal** [comment]
gshark-server

**Comment by BreakALegCml** [comment]
> gshark-server



> gshark-server

请问添加规则之后怎么知道gshark有没有开始扫描呢

**Comment by madneal** [comment]
看控制台打印的命令
