### ISSUE TITLE
docker-compose up -d重启后无法登陆

### ISSUE THREAD

**Issue by dead5nd** [madneal/gshark#196]
![image](https://github.com/madneal/gshark/assets/29460919/b1827f21-5c6e-42d8-982c-23782c2a4e1b)

**Comment by madneal** [comment]
检查下你的数据库容器

**Comment by dead5nd** [comment]
有bug，重新docker-compose up -d后，数据库没了，我遇到好几次了，每次都重新再来

**Comment by madneal** [comment]
因为是数据库容器的问题，数据库没有落到本地库，这个我后续看怎么落到本地吧
