### ISSUE TITLE
使用docker部署，数据库中好像没有创建对应的表

### ISSUE THREAD

**Issue by xiaqijun** [madneal/gshark#203]
![image](https://github.com/madneal/gshark/assets/130994988/718290b0-8eff-4f04-a9b3-6ccf436aff30)
使用docker部署，数据库中好像没有创建对应的表

**Comment by madneal** [comment]
这个应该是因为配置文件一开始使用的就是 docker 镜像，导致的没有触发初始化的操作，最新版本的应该已经修复了，你 docker-compose build 了吗

**Comment by xiaqijun** [comment]
我直接复制命令执行的
git clone https://github.com/madneal/gshark
cd gshark
docker-compose build && docker-compose up

**Comment by madneal** [comment]
你有 pull 最新的代码吗

**Comment by xiaqijun** [comment]
应该没有

**Comment by madneal** [comment]
拉最新的代码应该就好了
