### ISSUE TITLE
最新的docker版本搭建，默认gshark/gshark无法登录

### ISSUE THREAD

**Issue by xxsmile123** [madneal/gshark#204]
**Describe the bug**
使用gshark v1.4.4版本，通过docker方式搭建，默认密码：gshark/gshark无法登录。

**Screenshots**
<img width="1067" alt="image" src="https://github.com/madneal/gshark/assets/43473886/f95ae98f-548c-49fd-a645-97de49cc9efa">

**Comment by madneal** [comment]
拉一下最新的代码，最新版本已经修复了

**Comment by xxsmile123** [comment]
> 拉一下最新的代码，最新版本已经修复了

就是使用git clone获取最新的代码进行docker的构建。

**Comment by madneal** [comment]
我刚刚提交了代码修复了这个问题，主要是必须在 https://github.com/madneal/gshark/blob/master/server/config.docker.yaml 中声明一个不存在的 mysql 的地址，这样才能触发数据库的初始化操作。
