### ISSUE TITLE
gshark部署完，拉取github的api接口时，无法建立连接（token已添加且有效）

### ISSUE THREAD

**Issue by XingHuoLiaoYuanBaby** [madneal/gshark#212]
你好，我在windows本机部署的最新版本1.4.6，部署完成后，添加了github的token，且单独使用api测试可以正常拉取数据（挂了vpn），但是gshark控制台中显示，是不是控制台这块没挂上vpn的问题，或者单独使用还有啥技巧呢

[GShark]2024/07/25-15:55:59     error   Search error    {"github search error": "Get \"https://api.github.com/search/code?per_page=100&q=%E5%9B%BD%E7%BD%91%E5%AE%81%E5%A4%8F%E7%94%B5%E5%8A%9B+in%3Afile+%E6%BE%B3%E9%97%A8\": dial tcp 127.0.0.1:443: connectex: No connection could be made because the target machine actively refused it."}

![image](https://github.com/user-attachments/assets/f4bb8988-5de9-438e-a55f-5b06ccefa275)
![image](https://github.com/user-attachments/assets/073fbe67-a363-4297-b406-f582b8d5e22c)

**Comment by XingHuoLiaoYuanBaby** [comment]
噢，是我用的steam++加速器，加速github的时候选了hosts模式，直接把我本地hosts修改成了127.0.0.1。

**Comment by madneal** [comment]
每隔900秒睡眠一次
