### ISSUE TITLE
Cannot find module './view/task/task.vue'

### ISSUE THREAD

**Issue by wubainian** [madneal/gshark#213]
版本：[v1.4.6](https://github.com/madneal/gshark/releases/tag/v1.4.6)
当点击任务管理的时候，不能打开页面。**chrome查看cosole报错如下**：
```
vue-router.min.js:11 Error: Cannot find module './view/task/task.vue'
    at app.b0859975.js:1:20359
```
![企业微信截图_20240807173103](https://github.com/user-attachments/assets/ed7286ea-a715-41b7-a928-083404c1438d)

**Comment by madneal** [comment]
任务管理这个菜单已经没有了

**Comment by wubainian** [comment]
没有了之后，后台扫描任务的逻辑是什么呢？什么时间触发任务工作？

**Comment by madneal** [comment]
会有个循环，只要有规则和 token 就会持续扫描
