### ISSUE TITLE
docker 拉取部署初始化后，配置好token，没有跑出指定的 字段，就是跑不出结果

### ISSUE THREAD

**Issue by tang51678** [madneal/gshark#214]
docker 拉取的一切正常，没有报错们，就是不出结果，有大师傅，知道怎么解决的吗

**Comment by madneal** [comment]
配置好 token 和规则之后可能需要重启一下服务

**Comment by tang51678** [comment]
对了，大师傅，docker部署，里面跑子域名那个功能可以用不。










敢不敢
***@***.***

欢迎关注＂开心网安＂
15351410762



---原始邮件---
发件人: "Neal ***@***.***&gt;
发送时间: 2024年8月14日(周三) 晚上9:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [madneal/gshark] docker 拉取部署初始化后，配置好token，没有跑出指定的 字段，就是跑不出结果 (Issue #214)




 
配置好 token 和规则之后可能需要重启一下服务

**Comment by madneal** [comment]
应该不能，没有把 gobust 打包进去

**Comment by tang51678** [comment]
大师傅，您好，gitlab这个在最新版gshark跑有报错，这个docker要代码，在哪里改。本地部署也是这个样子。



GShark 在尝试从 GitLab API 进行全局搜索时遇到了问题。具体的错误信息是 403 Forbidden - Global Search is disabled for this scope，这表明 GitLab 的全局搜索功能在当前的作用域或配置下被禁用了。




tangkaixing
***@***.***

欢迎关注＂开心网安＂
15351410762




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "madneal/gshark"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月15日(星期四) 晚上9:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [madneal/gshark] docker 拉取部署初始化后，配置好token，没有跑出指定的 字段，就是跑不出结果 (Issue #214)





 
应该不能，没有把 gobust 打包进去

**Comment by madneal** [comment]
应该是 gitlab 把全局搜索禁用了，暂时无解决办法

**Comment by tang51678** [comment]
好的&nbsp; 谢谢 师傅




tangkaixing
***@***.***

欢迎关注＂开心网安＂
15351410762




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "madneal/gshark"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月20日(星期二) 上午10:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [madneal/gshark] docker 拉取部署初始化后，配置好token，没有跑出指定的 字段，就是跑不出结果 (Issue #214)





 
应该是 gitlab 把全局搜索禁用了，暂时无解决办法
