### ISSUE TITLE
直接docker拉取，build时提示services.scan.restart must be a string

### ISSUE THREAD

**Issue by Qianxingyue** [madneal/gshark#216]
ubuntu@ubuntu:\~$ git clone https://github.com/madneal/gshark
Cloning into 'gshark'...
remote: Enumerating objects: 12617, done.
remote: Counting objects: 100% (1992/1992), done.
remote: Compressing objects: 100% (1463/1463), done.
remote: Total 12617 (delta 543), reused 1890 (delta 517), pack-reused 10625 (fro m 1)
Receiving objects: 100% (12617/12617), 231.84 MiB | 454.00 KiB/s, done.
Resolving deltas: 100% (5691/5691), done.
ubuntu@ubuntu:\~$ cd gshark/
ubuntu@ubuntu:\~/gshark$ docker-compose build && docker-compose up
services.scan.restart must be a string
有知道这是为什么的么

**Comment by madneal** [comment]
https://github.com/madneal/gshark/blob/988312c14000e9c6486276e52afa2e74d3e97592/docker-compose.yaml#L79
检查下这个配置

**Comment by Qianxingyue** [comment]
> https://github.com/madneal/gshark/blob/988312c14000e9c6486276e52afa2e74d3e97592/docker-compose.yaml#L79
> 
> 
> 检查下这个配置

是要修改为yes么

**Comment by madneal** [comment]
```
restart: "no"
```

**Comment by WhatHowie** [comment]
把version改为2.1
