### ISSUE TITLE
【建议】代理配置和任务管理相关

### ISSUE THREAD

**Issue by vpxuser** [madneal/gshark#218]
1. 在管理后台新增代理配置，虽然知道可以进入容器通过设置环境变量配置代理，但是懒，哈哈
2. 由于新版已经删除了任务管理模块，所以不知道创建的规则有没有跑起来，还有一个问题是，任务过多时担心占用过的资源，希望能有任务管控

**Comment by madneal** [comment]
1. 这个不太适合通过系统配置
2. 任务是单任务，不会占用过多资源，任务运行可以通过控制台观察
