### ISSUE TITLE
don't show any result

### ISSUE THREAD

**Issue by k3mlol** [madneal/gshark#229]
**Describe the bug**
source code leak result doesn't show,
I already used the latest release version, move dist/ to the /var/www/html/ folder

**Screenshots**
<img width="1125" alt="image" src="https://github.com/user-attachments/assets/86db078d-b9d2-4e69-a7f5-cdb17dc5ecae" />

**Comment by madneal** [comment]
you need to start the scan service, and config rules and tokens for the scan service.

**Comment by k3mlol** [comment]
Hi @madneal, the backend is running
<img width="1055" alt="image" src="https://github.com/user-attachments/assets/34f47c9e-07e3-493f-954b-b7e662241c8c" />
I already have some result.
<img width="1169" alt="image" src="https://github.com/user-attachments/assets/3b8a8173-d669-4fcb-af63-ae56cf7f73d9" />

**Comment by madneal** [comment]
scan service is total a different service, plz read README carefully.
