### ISSUE TITLE
go build问题

### ISSUE THREAD

**Issue by sfdota** [madneal/gshark#59]
go build 问题出现github.com/PuerkitoBio/goquery@v1.5.0: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.5.0.mod": dial tcp 172.217.160.113:443: i/o timeout

**Comment by madneal** [comment]
应该是你的网络问题吧，拉不到依赖包，可以参考这篇文章配置代理

https://madneal.com/post/gproxy/
