### ISSUE TITLE
新版本报错

### ISSUE THREAD

**Issue by soldier3r** [madneal/gshark#63]
linux版本：
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.8.2003 (Core)
Release:        7.8.2003
Codename:       Core
app.ini配置：
;rename this file to app.ini to use
HTTP_HOST = 0.0.0.0
HTTP_PORT = 5000
MAX_INDEXERS = 2
; server酱配置口令
SCKEY = Sxxxx
; gobuster file path
gobuster_path =
; gobuster subdomain wordlist file path
subdomain_wordlist_file =

[database]
;support sqlite, mysql, postgres
DB_TYPE = sqlite
HOST = 127.0.0.1
PORT = 3306
;database name
NAME = gshark
;username and password
USER = root
PASSWD =
SSL_MODE = disable
;the path to store the database file of sqlite3, ignore this for other database
PATH =

goproxy:
go env -w GOPROXY=https://goproxy.cn,direct
go env -w GO111MODULE=on

执行：
./main scan
报错如下：
search with the query:xxx +in:file -extension:.ico -extension:.flv -extension:.css -extension:.jpg -extension:.png -extension:.jpeg -extension:.gif -extension:.pdf -extension:.ss3 -extension:.rar -extension:.zip -extension:.avi -extension:.mp4 -extension:.swf -extension:.wmi -extension:.exe -extension:.mpeg -extension:.dll -extension:.pcap -extension:.log -extension:.class -extension:.html -language:html -language:smail -language:jsp
runtime: program exceeds 10000-thread limit
fatal error: thread exhaustion

runtime stack:
runtime.throw(0xe9d9c9, 0x11)
	/usr/lib/golang/src/runtime/panic.go:1116 +0x72
runtime.checkmcount()
	/usr/lib/golang/src/runtime/proc.go:622 +0xac
runtime.mReserveID(0x1728b78)
	/usr/lib/golang/src/runtime/proc.go:636 +0x3e
runtime.startm(0xc00002e800, 0x1728b00)
	/usr/lib/golang/src/runtime/proc.go:1957 +0x79
runtime.handoffp(0xc00002e800)
	/usr/lib/golang/src/runtime/proc.go:1993 +0x52
runtime.retake(0x10d4658f367b6a, 0xc00002e800)
	/usr/lib/golang/src/runtime/proc.go:4805 +0x168
runtime.sysmon()
	/usr/lib/golang/src/runtime/proc.go:4713 +0x1b1
runtime.mstart1()
	/usr/lib/golang/src/runtime/proc.go:1172 +0xc8
runtime.mstart()
	/usr/lib/golang/src/runtime/proc.go:1137 +0x6e

goroutine 1 [runnable]:
github.com/madneal/gshark/search.Scan(0xc000223600)
	/home/xxxx/gshark/search/scan.go:62 +0x164
github.com/urfave/cli.HandleAction(0xd19840, 0xed6ff8, 0xc000223600, 0xc000219100, 0x0)
	/root/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:492 +0xc2
github.com/urfave/cli.Command.Run(0xe8e27d, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0xea36aa, 0x17, 0x0, ...)
	/root/go/pkg/mod/github.com/urfave/cli@v1.20.0/command.go:210 +0x9fb
github.com/urfave/cli.(*App).Run(0xc000204b60, 0xc00000e0a0, 0x2, 0x2, 0x0, 0x0)
	/root/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:255 +0x768
main.main()
	/home/xxxx/gshark/main.go:25 +0x34b

goroutine 6 [select]:
database/sql.(*DB).connectionOpener(0xc000179110, 0xf9d920, 0xc000065880)
	/usr/lib/golang/src/database/sql/sql.go:1126 +0xf5
created by database/sql.OpenDB
	/usr/lib/golang/src/database/sql/sql.go:740 +0x12a

goroutine 7 [semacquire]:
sync.runtime_Semacquire(0xc00009abe8)
	/usr/lib/golang/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc00009abe0)
	/usr/lib/golang/src/sync/waitgroup.go:130 +0x65
github.com/madneal/gshark/search/githubsearch.Search(0xc000090e40, 0x1, 0x1)
	/home/xxxx/gshark/search/githubsearch/search.go:55 +0x1e5
github.com/madneal/gshark/search/githubsearch.RunSearchTask(0xc000093530, 0x0, 0x0)
	/home/xxxx/gshark/search/githubsearch/search.go:66 +0x119
github.com/madneal/gshark/search/githubsearch.RunTask(0x384)
	/home/xxxx/gshark/search/githubsearch/search.go:130 +0x2b
created by github.com/madneal/gshark/search.Scan
	/home/xxxx/gshark/search/scan.go:61 +0x15d

goroutine 167 [select]:
net/http.(*Transport).getConn(0x1630e20, 0xc0000b4a00, 0x0, 0xc0000dca00, 0x5, 0xc00009cc00, 0x12, 0x0, 0x0, 0x0, ...)
	/usr/lib/golang/src/net/http/transport.go:1347 +0x5ac
net/http.(*Transport).roundTrip(0x1630e20, 0xc0000de800, 0xc0005846d0, 0xc000580e30, 0xed7fd0)
	/usr/lib/golang/src/net/http/transport.go:569 +0x77c
net/http.(*Transport).RoundTrip(0x1630e20, 0xc0000de800, 0xc0000de800, 0x0, 0x41b390)
	/usr/lib/golang/src/net/http/roundtrip.go:17 +0x35
golang.org/x/oauth2.(*Transport).RoundTrip(0xc000580e10, 0xc0000de700, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/golang.org/x/oauth2@v0.0.0-20190604053449-0f29369cfe45/transport.go:56 +0x192
net/http.send(0xc0000de700, 0xf8bac0, 0xc000580e10, 0x0, 0x0, 0x0, 0xc0000a81f0, 0x41b390, 0x1, 0x0)
	/usr/lib/golang/src/net/http/client.go:252 +0x453
net/http.(*Client).send(0xc000580e40, 0xc0000de700, 0x0, 0x0, 0x0, 0xc0000a81f0, 0x0, 0x1, 0x203000)
	/usr/lib/golang/src/net/http/client.go:176 +0xff
net/http.(*Client).do(0xc000580e40, 0xc0000de700, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/net/http/client.go:718 +0x45f
net/http.(*Client).Do(...)
	/usr/lib/golang/src/net/http/client.go:586
github.com/google/go-github/github.(*Client).Do(0xc0000b9040, 0xf9d960, 0xc000022658, 0xc0000de600, 0xd6c040, 0xc000581320, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/github.com/google/go-github@v17.0.0+incompatible/github/github.go:473 +0x227
github.com/google/go-github/github.(*SearchService).search(0xc0000b90c8, 0xf9d960, 0xc000022658, 0xe8df15, 0x4, 0xc0000fbc48, 0xc0000b49c0, 0xd6c040, 0xc000581320, 0x0, ...)
	/root/go/pkg/mod/github.com/google/go-github@v17.0.0+incompatible/github/search.go:260 +0x373
github.com/google/go-github/github.(*SearchService).Code(0xc0000b90c8, 0xf9d960, 0xc000022658, 0xc0000d7340, 0x1a2, 0xc0000b49c0, 0xc000124080, 0x1, 0xc0000fbcd8, 0x507b31)
	/root/go/pkg/mod/github.com/google/go-github@v17.0.0+incompatible/github/search.go:184 +0xe5
github.com/madneal/gshark/search/githubsearch.searchCodeByOpt(0xc000582e40, 0xf9d960, 0xc000022658, 0xc0000d7340, 0x1a2, 0xe9234f, 0x7, 0xe8df55, 0x4, 0x1, ...)
	/home/xxxx/gshark/search/githubsearch/search.go:192 +0xd4
github.com/madneal/gshark/search/githubsearch.(*Client).SearchCode(0xc000582e40, 0xc00009b3d0, 0x6, 0xafe1b6, 0xe9089a, 0x6, 0x0, 0x0)
	/home/xxxx/gshark/search/githubsearch/search.go:149 +0x2cb
github.com/madneal/gshark/search/githubsearch.Search.func1(0xc00009b400, 0xc000582e40, 0xc000584390, 0x1, 0x0, 0x0, 0xc00009b3b0, 0x6, 0xc00009b3d0, 0x6, ...)
	/home/xxxx/gshark/search/githubsearch/search.go:44 +0xdf
created by github.com/madneal/gshark/search/githubsearch.Search
	/home/xxxx/gshark/search/githubsearch/search.go:42 +0x1b8

goroutine 9 [semacquire]:
sync.runtime_Semacquire(0xc00009b408)
	/usr/lib/golang/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc00009b400)
	/usr/lib/golang/src/sync/waitgroup.go:130 +0x65
github.com/madneal/gshark/search/githubsearch.Search(0xc0000918c0, 0x1, 0x1)
	/home/xxxx/gshark/search/githubsearch/search.go:55 +0x1e5
github.com/madneal/gshark/search/githubsearch.RunSearchTask(0xc0005806f0, 0x0, 0x0)
	/home/xxxx/gshark/search/githubsearch/search.go:66 +0x119
github.com/madneal/gshark/search/githubsearch.RunTask(0x384)
	/home/xxxx/gshark/search/githubsearch/search.go:130 +0x2b
created by github.com/madneal/gshark/search.Scan
	/home/xxxx/gshark/search/scan.go:61 +0x15d

goroutine 169 [select]:
net/http.(*Transport).getConn(0x1630e20, 0xc0000b4e80, 0x0, 0xc0000dcc00, 0x5, 0xc00009cfe0, 0x12, 0x0, 0x0, 0x0, ...)
	/usr/lib/golang/src/net/http/transport.go:1347 +0x5ac
net/http.(*Transport).roundTrip(0x1630e20, 0xc0000deb00, 0xc000585610, 0xc00058a290, 0xed7fd0)
	/usr/lib/golang/src/net/http/transport.go:569 +0x77c
net/http.(*Transport).RoundTrip(0x1630e20, 0xc0000deb00, 0xc0000deb00, 0x0, 0x41b390)
	/usr/lib/golang/src/net/http/roundtrip.go:17 +0x35
golang.org/x/oauth2.(*Transport).RoundTrip(0xc00058a270, 0xc0000dea00, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/golang.org/x/oauth2@v0.0.0-20190604053449-0f29369cfe45/transport.go:56 +0x192
net/http.send(0xc0000dea00, 0xf8bac0, 0xc00058a270, 0x0, 0x0, 0x0, 0xc0000a82c0, 0x41b390, 0x1, 0x0)
	/usr/lib/golang/src/net/http/client.go:252 +0x453
net/http.(*Client).send(0xc00058a2a0, 0xc0000dea00, 0x0, 0x0, 0x0, 0xc0000a82c0, 0x0, 0x1, 0x203000)
	/usr/lib/golang/src/net/http/client.go:176 +0xff
net/http.(*Client).do(0xc00058a2a0, 0xc0000dea00, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/net/http/client.go:718 +0x45f
net/http.(*Client).Do(...)
	/usr/lib/golang/src/net/http/client.go:586
github.com/google/go-github/github.(*Client).Do(0xc0000b97c0, 0xf9d960, 0xc000022658, 0xc0000de900, 0xd6c040, 0xc00058a780, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/github.com/google/go-github@v17.0.0+incompatible/github/github.go:473 +0x227
github.com/google/go-github/github.(*SearchService).search(0xc0000b9848, 0xf9d960, 0xc000022658, 0xe8df15, 0x4, 0xc00036bc48, 0xc0000b4e40, 0xd6c040, 0xc00058a780, 0x0, ...)
	/root/go/pkg/mod/github.com/google/go-github@v17.0.0+incompatible/github/search.go:260 +0x373
github.com/google/go-github/github.(*SearchService).Code(0xc0000b9848, 0xf9d960, 0xc000022658, 0xc0000d7c00, 0x1a2, 0xc0000b4e40, 0xc000124080, 0x1, 0xc00036bcd8, 0x507b31)
	/root/go/pkg/mod/github.com/google/go-github@v17.0.0+incompatible/github/search.go:184 +0xe5
github.com/madneal/gshark/search/githubsearch.searchCodeByOpt(0xc00058c140, 0xf9d960, 0xc000022658, 0xc0000d7c00, 0x1a2, 0xe9234f, 0x7, 0xe8df55, 0x4, 0x1, ...)
	/home/xxxx/gshark/search/githubsearch/search.go:192 +0xd4
github.com/madneal/gshark/search/githubsearch.(*Client).SearchCode(0xc00058c140, 0xc00009bca0, 0x6, 0xafe1b6, 0xe9089a, 0x6, 0x0, 0x0)
	/home/xxxx/gshark/search/githubsearch/search.go:149 +0x2cb
github.com/madneal/gshark/search/githubsearch.Search.func1(0xc00009bcd0, 0xc00058c140, 0xc0005852d0, 0x1, 0x0, 0x0, 0xc00009bc80, 0x6, 0xc00009bca0, 0x6, ...)
	/home/xxxx/gshark/search/githubsearch/search.go:44 +0xdf
created by github.com/madneal/gshark/search/githubsearch.Search
	/home/xxxx/gshark/search/githubsearch/search.go:42 +0x1b8

goroutine 11 [semacquire]:
sync.runtime_Semacquire(0xc00009a1b8)
	/usr/lib/golang/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc00009a1b0)
	/usr/lib/golang/src/sync/waitgroup.go:130 +0x65
github.com/madneal/gshark/search/githubsearch.Search(0xc0000901e0, 0x1, 0x1)
	/home/xxxx/gshark/search/githubsearch/search.go:55 +0x1e5
github.com/madneal/gshark/search/githubsearch.RunSearchTask(0xc000092000, 0x0, 0x0)
	/home/xxxx/gshark/search/githubsearch/search.go:66 +0x119
github.com/madneal/gshark/search/githubsearch.RunTask(0x384)
	/home/xxxx/gshark/search/githubsearch/search.go:130 +0x2b
created by github.com/madneal/gshark/search.Scan
	/home/xxxx/gshark/search/scan.go:61 +0x15d

goroutine 547 [select]:
net.(*Resolver).lookupIPAddr(0x1727a40, 0xf9d9a0, 0xc000310960, 0xe8d6ef, 0x3, 0xc000314360, 0xe, 0x1bb, 0x0, 0x0, ...)
	/usr/lib/golang/src/net/lookup.go:299 +0x685
net.(*Resolver).internetAddrList(0x1727a40, 0xf9d9a0, 0xc000310960, 0xe8d6ef, 0x3, 0xc000314360, 0x12, 0x0, 0x0, 0x0, ...)
	/usr/lib/golang/src/net/ipsock.go:280 +0x4d4
net.(*Resolver).resolveAddrList(0x1727a40, 0xf9d9a0, 0xc000310960, 0xe8df5d, 0x4, 0xe8d6ef, 0x3, 0xc000314360, 0x12, 0x0, ...)
	/usr/lib/golang/src/net/dial.go:221 +0x47d
net.(*Dialer).DialContext(0xc000066480, 0xf9d960, 0xc000022658, 0xe8d6ef, 0x3, 0xc000314360, 0x12, 0x0, 0x0, 0x0, ...)
	/usr/lib/golang/src/net/dial.go:403 +0x22b
net/http.(*Transport).dial(0x1630e20, 0xf9d960, 0xc000022658, 0xe8d6ef, 0x3, 0xc000314360, 0x12, 0x0, 0x0, 0x0, ...)
	/usr/lib/golang/src/net/http/transport.go:1141 +0x1fd
net/http.(*Transport).dialConn(0x1630e20, 0xf9d960, 0xc000022658, 0x0, 0xc00035e000, 0x5, 0xc000314360, 0x12, 0x0, 0xc000332120, ...)
	/usr/lib/golang/src/net/http/transport.go:1575 +0x1abb
net/http.(*Transport).dialConnFor(0x1630e20, 0xc000362000)
	/usr/lib/golang/src/net/http/transport.go:1421 +0xc6
created by net/http.(*Transport).queueForDial
	/usr/lib/golang/src/net/http/transport.go:1390 +0x40f

goroutine 13 [semacquire]:
sync.runtime_Semacquire(0xc000292228)
	/usr/lib/golang/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc000292220)
	/usr/lib/golang/src/sync/waitgroup.go:130 +0x65
github.com/madneal/gshark/search/githubsearch.Search(0xc000290240, 0x1, 0x1)
	/home/xxxx/gshark/search/githubsearch/search.go:55 +0x1e5
github.com/madneal/gshark/search/githubsearch.RunSearchTask(0xc00028c180, 0x0, 0x0)
	/home/xxxx/gshark/search/githubsearch/search.go:66 +0x119
github.com/madneal/gshark/search/githubsearch.RunTask(0x384)
	/home/xxxx/gshark/search/githubsearch/search.go:130 +0x2b
created by github.com/madneal/gshark/search.Scan
	/home/xxxx/gshark/search/scan.go:61 +0x15d

goroutine 546 [select]:
net/http.(*Transport).getConn(0x1630e20, 0xc000322380, 0x0, 0xc00035e000, 0x5, 0xc000314360, 0x12, 0x0, 0x0, 0x0, ...)
	/usr/lib/golang/src/net/http/transport.go:1347 +0x5ac
net/http.(*Transport).roundTrip(0x1630e20, 0xc000360200, 0xc00030ee10, 0xc00030cc20, 0xed7fd0)
	/usr/lib/golang/src/net/http/transport.go:569 +0x77c
net/http.(*Transport).RoundTrip(0x1630e20, 0xc000360200, 0xc000360200, 0x0, 0x41b390)
	/usr/lib/golang/src/net/http/roundtrip.go:17 +0x35
golang.org/x/oauth2.(*Transport).RoundTrip(0xc00030cc00, 0xc000360100, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/golang.org/x/oauth2@v0.0.0-20190604053449-0f29369cfe45/transport.go:56 +0x192
net/http.send(0xc000360100, 0xf8bac0, 0xc00030cc00, 0x0, 0x0, 0x0, 0xc0003200c8, 0x41b390, 0x1, 0x0)
	/usr/lib/golang/src/net/http/client.go:252 +0x453
net/http.(*Client).send(0xc00030cc30, 0xc000360100, 0x0, 0x0, 0x0, 0xc0003200c8, 0x0, 0x1, 0x203000)
	/usr/lib/golang/src/net/http/client.go:176 +0xff
net/http.(*Client).do(0xc00030cc30, 0xc000360100, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/net/http/client.go:718 +0x45f
net/http.(*Client).Do(...)
	/usr/lib/golang/src/net/http/client.go:586
github.com/google/go-github/github.(*Client).Do(0xc00033a140, 0xf9d960, 0xc000022658, 0xc000360000, 0xd6c040, 0xc00030d110, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/github.com/google/go-github@v17.0.0+incompatible/github/github.go:473 +0x227
github.com/google/go-github/github.(*SearchService).search(0xc00033a1c8, 0xf9d960, 0xc000022658, 0xe8df15, 0x4, 0xc0002a1c48, 0xc000322340, 0xd6c040, 0xc00030d110, 0x0, ...)
	/root/go/pkg/mod/github.com/google/go-github@v17.0.0+incompatible/github/search.go:260 +0x373
github.com/google/go-github/github.(*SearchService).Code(0xc00033a1c8, 0xf9d960, 0xc000022658, 0xc000358000, 0x1a2, 0xc000322340, 0xc000124180, 0x3, 0xc0002a1cd8, 0x507b31)
	/root/go/pkg/mod/github.com/google/go-github@v17.0.0+incompatible/github/search.go:184 +0xe5
github.com/madneal/gshark/search/githubsearch.searchCodeByOpt(0xc000308cc0, 0xf9d960, 0xc000022658, 0xc000358000, 0x1a2, 0xe9234f, 0x7, 0xe8df55, 0x4, 0x1, ...)
	/home/xxxx/gshark/search/githubsearch/search.go:192 +0xd4
github.com/madneal/gshark/search/githubsearch.(*Client).SearchCode(0xc000308cc0, 0xc000312270, 0x6, 0xafe1b6, 0xe9089a, 0x6, 0x0, 0x0)
	/home/xxxx/gshark/search/githubsearch/search.go:149 +0x2cb
github.com/madneal/gshark/search/githubsearch.Search.func1(0xc0003122a0, 0xc000308cc0, 0xc00030ead0, 0x1, 0x0, 0x0, 0xc000312250, 0x6, 0xc000312270, 0x6, ...)
	/home/xxxx/gshark/search/githubsearch/search.go:44 +0xdf
created by github.com/madneal/gshark/search/githubsearch.Search
	/home/xxxx/gshark/search/githubsearch/search.go:42 +0x1b8

goroutine 15 [semacquire]:
sync.runtime_Semacquire(0xc0003122a8)
	/usr/lib/golang/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc0003122a0)
	/usr/lib/golang/src/sync/waitgroup.go:130 +0x65
github.com/madneal/gshark/search/githubsearch.Search(0xc0003102a0, 0x1, 0x1)
	/home/xxxx/gshark/search/githubsearch/search.go:55 +0x1e5
github.com/madneal/gshark/search/githubsearch.RunSearchTask(0xc00030c4e0, 0x0, 0x0)
	/home/xxxx/gshark/search/githubsearch/search.go:66 +0x119
github.com/madneal/gshark/search/githubsearch.RunTask(0x384)
	/home/xxxx/gshark/search/githubsearch/search.go:130 +0x2b
created by github.com/madneal/gshark/search.Scan
	/home/xxxx/gshark/search/scan.go:61 +0x15d

goroutine 548 [select]:
net/http.(*Transport).getConn(0x1630e20, 0xc0003227c0, 0x0, 0xc00035e200, 0x5, 0xc0003146e0, 0x12, 0x0, 0x0, 0x0, ...)
	/usr/lib/golang/src/net/http/transport.go:1347 +0x5ac
net/http.(*Transport).roundTrip(0x1630e20, 0xc000360500, 0xc00030fc60, 0xc00030ddc0, 0xed7fd0)
	/usr/lib/golang/src/net/http/transport.go:569 +0x77c
net/http.(*Transport).RoundTrip(0x1630e20, 0xc000360500, 0xc000360500, 0x0, 0x41b390)
	/usr/lib/golang/src/net/http/roundtrip.go:17 +0x35
golang.org/x/oauth2.(*Transport).RoundTrip(0xc00030dda0, 0xc000360400, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/golang.org/x/oauth2@v0.0.0-20190604053449-0f29369cfe45/transport.go:56 +0x192
net/http.send(0xc000360400, 0xf8bac0, 0xc00030dda0, 0x0, 0x0, 0x0, 0xc000320190, 0x41b390, 0x1, 0x0)
	/usr/lib/golang/src/net/http/client.go:252 +0x453
net/http.(*Client).send(0xc00030ddd0, 0xc000360400, 0x0, 0x0, 0x0, 0xc000320190, 0x0, 0x1, 0x203000)
	/usr/lib/golang/src/net/http/client.go:176 +0xff
net/http.(*Client).do(0xc00030ddd0, 0xc000360400, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/net/http/client.go:718 +0x45f
net/http.(*Client).Do(...)
	/usr/lib/golang/src/net/http/client.go:586
github.com/google/go-github/github.(*Client).Do(0xc00033a8c0, 0xf9d960, 0xc000022658, 0xc000360300, 0xd6c040, 0xc0003642d0, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/github.com/google/go-github@v17.0.0+incompatible/github/github.go:473 +0x227
github.com/google/go-github/github.(*SearchService).search(0xc00033a948, 0xf9d960, 0xc000022658, 0xe8df15, 0x4, 0xc0002edc48, 0xc000322780, 0xd6c040, 0xc0003642d0, 0x0, ...)
	/root/go/pkg/mod/github.com/google/go-github@v17.0.0+incompatible/github/search.go:260 +0x373
github.com/google/go-github/github.(*SearchService).Code(0xc00033a948, 0xf9d960, 0xc000022658, 0xc000358a80, 0x1a2, 0xc000322780, 0xc000124180, 0x3, 0xc0002edcd8, 0x507b31)
	/root/go/pkg/mod/github.com/google/go-github@v17.0.0+incompatible/github/search.go:184 +0xe5
github.com/madneal/gshark/search/githubsearch.searchCodeByOpt(0xc000309ea0, 0xf9d960, 0xc000022658, 0xc000358a80, 0x1a2, 0xe9234f, 0x7, 0xe8df55, 0x4, 0x1, ...)
	/home/xxxx/gshark/search/githubsearch/search.go:192 +0xd4
github.com/madneal/gshark/search/githubsearch.(*Client).SearchCode(0xc000309ea0, 0xc000312a90, 0x6, 0xafe1b6, 0xe9089a, 0x6, 0x0, 0x0)
	/home/xxxx/gshark/search/githubsearch/search.go:149 +0x2cb
github.com/madneal/gshark/search/githubsearch.Search.func1(0xc000312ac0, 0xc000309ea0, 0xc00030f920, 0x1, 0x0, 0x0, 0xc000312a70, 0x6, 0xc000312a90, 0x6, ...)
	/home/xxxx/gshark/search/githubsearch/search.go:44 +0xdf
created by github.com/madneal/gshark/search/githubsearch.Search
	/home/xxxx/gshark/search/githubsearch/search.go:42 +0x1b8

**Comment by madneal** [comment]
可能是由于 goroutine 的关系吧，已经移除 go 关键词了
