### ISSUE TITLE
User数据初始化问题

### ISSUE THREAD

**Issue by WillieMatthewLiu** [madneal/gshark#73]
大佬，貌似缺少User用户的初始化过程

**Comment by WillieMatthewLiu** [comment]
API表中存在重复的主键121

**Comment by madneal** [comment]
应该是因为你一开始数据库初始化失败了，建议你先删掉之前的数据库，然后重新init

**Comment by WillieMatthewLiu** [comment]
> 应该是因为你一开始数据库初始化失败了，建议你先删掉之前的数据库，然后重新init

source/api.go中定义的初始化数据，有两个ID是121的，所以会导致数据初始化失败

**Comment by madneal** [comment]
@WillieMatthewLiu  谢谢提醒，不过应该只影响一条数据
