### ISSUE TITLE
数据库初始化错误

### ISSUE THREAD

**Issue by F0x01** [madneal/gshark#75]
root:eSSSSSS59@tcp(127.0.0.1:3306)/
config file changed: ./config.yaml

[Mysql] --> sys_users 表初始数据成功!

[Mysql] --> sys_apis 表初始数据成功!

2021/04/24 00:10:57 /Users/neal/project/gshark/server/source/authority_menu.go:16 Error 1146: Table 'gshark.authority_menu' doesn't exist
[1.870ms] [rows:0] SELECT * FROM `authority_menu` WHERE `authority_menu`.`deleted_at` IS NULL

[Mysql] --> authority_menu 视图创建成功!

[Mysql] --> sys_authorities 表初始数据成功!

[Mysql] --> sys_authority_menus 表初始数据成功!

[Mysql] --> casbin_rule 表初始数据成功!

[Mysql] --> sys_data_authority_id 表初始数据成功!

[Mysql] --> sys_dictionaries 表初始数据成功!

[Mysql] --> sys_dictionary_details 表初始数据成功!

[Mysql] --> exa_file_upload_and_downloads 表初始数据成功!

[Mysql] --> sys_base_menus 表初始数据成功!

**Comment by F0x01** [comment]
初始化完之后没有菜单，建议可以提供一个数据库或者配好的docker镜像，docker一键拉取就能用不用再来配nginx 配mysql，感谢大佬

**Comment by madneal** [comment]
数据库版本要5.6以上，目前并不需要什么复杂的配置，也没有docker支持的计划

**Comment by madneal** [comment]
这个问题已经通过最新的 release 修复了，建视图可能需要权限，我目前用的 root，后续我再看看
