### ISSUE TITLE
七牛 AK 泄漏

### ISSUE THREAD

**Issue by imlonghao** [madneal/gshark#76]
https://github.com/madneal/gshark/blob/85808f6d3879e7382baec689b711bf7f6a0d7ce2/server/config-temp.yaml#L52-L53

测试了一下这个 AK 是可以用的，权限似乎也挺高，能够创建 bucket（为了测试我创建了一个空的 bucket 名为 `hello-gshark`），能够访问帐号下的两个 bucket

通过给 bucket 上传文件能够控制 http://qmplusimg.henrongyi.top/ 域名下的内容

AK 在 https://github.com/madneal/gshark/commit/934c7624f66a5df98353ce213269cf3e39e915be 被引入

建议 Revoke 掉这个 AK

---

（一个扫敏感信息泄漏的项目自己就引入了敏感信息到项目中）

**Comment by madneal** [comment]
@imlonghao 这个 bucket 也是别人开源项目公开给别人使用的哈，不过因我们项目目前也不需要使用，后续我可能会移除吧
