### ISSUE TITLE
关于Gshark使用中的相关问题

### ISSUE THREAD

**Issue by bycimi** [madneal/gshark#80]
麻烦问一下大佬，邮箱配置的作用是什么？是在扫到敏感信息时邮件通知么？但是我配置完成之后扫到敏感信息并没有发邮件。
还有就是我配置好token之后进行扫描时，扫描完成但是没有结果。
![图片](https://user-images.githubusercontent.com/52587366/116060081-1b766480-a6b4-11eb-8b06-0b5f6d6816bd.png)

**Comment by madneal** [comment]
你这个都是没有搜到结果的，就是没结果，邮箱推荐使用 qq邮箱，要配置授权码的，页面上可以测试

**Comment by bycimi** [comment]
但是同样的关键词我用之前没有进行前后端分离的软件可以搜到结果，是不是我那个地方配置有问题？

**Comment by bycimi** [comment]
![image](https://user-images.githubusercontent.com/56858714/116643072-da779c00-a9a2-11eb-8a76-b76d3488445b.png)
这是最新报错截图，麻烦您了

**Comment by madneal** [comment]
@bycimi 这个是 fork的问题，现在 fork已经没有false这个值了，这给分体已经修复了，这个报错可能是你的 token 有问题

**Comment by madneal** [comment]
@bycimi 422 是一个 bug，现在修复了

**Comment by Hechangan** [comment]
session是永远不过期的吗，怎么设置session的有效期

**Comment by madneal** [comment]
通过 jwt 实现的，https://github.com/madneal/gshark/blob/4bc9f9c75fc790ce2042bc1177dd4fba3089549f/server/config/jwt.go，
可以去配的
