### ISSUE TITLE
Linux初始化404

### ISSUE THREAD

**Issue by yhy0** [madneal/gshark#81]
![image](https://user-images.githubusercontent.com/31311038/118783778-f8f5f680-b8c1-11eb-96e2-66bb36a08776.png)
![image](https://user-images.githubusercontent.com/31311038/118783817-03b08b80-b8c2-11eb-9946-c4e8c63eaf7d.png)

**Comment by madneal** [comment]
是不是以前初始化过，确定用的是最新版

**Comment by yhy0** [comment]
最新版的, 之前没有初始化过，
![image](https://user-images.githubusercontent.com/31311038/118784767-e03a1080-b8c2-11eb-9585-4dd1285d2f91.png)
不止初始化界面有404提示
![image](https://user-images.githubusercontent.com/31311038/118784870-f051f000-b8c2-11eb-9c38-5cfa201d0838.png)

**Comment by madneal** [comment]
数据库并没有初始化成功

**Comment by yhy0** [comment]
对，点击初始化，就提示404

**Comment by madneal** [comment]
可不可以把日志打多一点，还有确保你的数据库用户名密码是对的，并且有创建数据库的权限

**Comment by yhy0** [comment]
![image](https://user-images.githubusercontent.com/31311038/118785668-a61d3e80-b8c3-11eb-9701-67a0c8de0435.png)
这个api是不是有问题，
我没有把项目放到NGINX的默认目录下，又创建了一层目录，我把那层目录加上访问api也是404，config.yml

日志只有这么多，是不是我nginx 配错了，服务端没反应，数据库是root，且没有密码
![image](https://user-images.githubusercontent.com/31311038/118787001-f648d080-b8c4-11eb-9795-76b3afa48581.png)

**Comment by madneal** [comment]
![image](https://user-images.githubusercontent.com/12164075/118787914-db2a9080-b8c5-11eb-8bd5-4ae0818af68a.png)

我自己在 linux 上面的配置

**Comment by yhy0** [comment]
OK了，我NGINX不知道哪个错了，照抄师傅的可以了，多谢师傅
