### ISSUE TITLE
更新最新版本后登出用户后再次登录就报500

### ISSUE THREAD

**Issue by Hechangan** [madneal/gshark#83]
我更新了之后新版本。
在系统中登出后再次登录发现

runtime error: invalid memory address or nil pointer dereference
![image](https://user-images.githubusercontent.com/53103631/133741031-c5a9e451-7002-47ce-8f49-393de7d4b714.png)

**Comment by madneal** [comment]
数据库配置，配置文件改了吗

**Comment by madneal** [comment]
confgi.yaml 记得替换一下，用你以前的

**Comment by wanroua** [comment]
centos 初始化失败![image](https://user-images.githubusercontent.com/38250590/135285848-03dba4e0-99b8-4e6b-a8f1-2e8f58e4a036.png)

**Comment by xj90512** [comment]
问题仍然出现了，config也替换成之前的了， 找不到原因啊，访问数据库是没问题的
