### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by c9oogle** [madneal/gshark#87]
运行./gshark scan时，提示：
[GShark]2021/11/22 - 14:55:04.386	error	Search error	{"github search error": "Get \"https://api.github.com/search/code?q=xxx+in:file&order=desc&per_page=100&sort=indexed\": x509: certificate signed by unknown authority"}

排查了很久，发现可能是公司网络的问题，切换到个人热点或其他外部的网络可以正常运行，希望能在管理后台增加一个"忽略证书错误"的配置选项，或者在代码直接添加忽略

**Comment by madneal** [comment]
https://github.com/google/go-github/issues/1439

理论上可以实现的，需要做一些改造

**Comment by madneal** [comment]
最新版本已经支持了
