### ISSUE TITLE
请问GitHub这个次数限制有方法绕过吗

### ISSUE THREAD

**Issue by tao1tao** [madneal/gshark#89]
"github search error": "GET https://api.github.com/search/code?q=password+in:file+-extension:css+-extension:png+-extension:md&order=desc&page=2&per_page=100&sort=indexed: 403 You have exceeded a secondary rate limit. Please wait a few minutes before you try again. []"请问GitHub次数限制怎样突破呢

**Comment by madneal** [comment]
理论上可以通过多个账号的 token 也许能实现，但是我们这个项目没有做这样的绕过，因为实际经验来看，一般这种扫描实时要求没这么高

**Comment by leeloveying** [comment]
> 理论上可以通过多个账号的 token 也许能实现，但是我们这个项目没有做这样的绕过，因为实际经验来看，一般这种扫描实时要求没这么高

麻烦问下，失败的会进行扫描重试吗？

**Comment by madneal** [comment]
会

**Comment by madneal** [comment]
Github现在速率限制非常严格，而且绕过具有很大风险，也不建议使用多账号的方式，这种都有可能有封号的风险
